//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.LogCabin.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.LogCabin.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for playing the Log Cabin!.
        /// </summary>
        internal static string CLOSING {
            get {
                return ResourceManager.GetString("CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by me..
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du befindest Dich in einem Wohnraum..
        /// </summary>
        internal static string LIVINGROOM {
            get {
                return ResourceManager.GetString("LIVINGROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Log Cabin!.
        /// </summary>
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das bist Du..
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalte das Licht an..
        /// </summary>
        internal static string QUEST_I {
            get {
                return ResourceManager.GetString("QUEST_I", resourceCulture);
            }
        }
    }
}
