//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Test.TestResources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.Test.TestResources.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CHEST {
            get {
                return ResourceManager.GetString("CHEST", resourceCulture);
            }
        }
        
        internal static string PLANK {
            get {
                return ResourceManager.GetString("PLANK", resourceCulture);
            }
        }
        
        internal static string DOOR {
            get {
                return ResourceManager.GetString("DOOR", resourceCulture);
            }
        }
        
        internal static string IRON_KEY {
            get {
                return ResourceManager.GetString("IRON_KEY", resourceCulture);
            }
        }
        
        internal static string KEY_HOLE {
            get {
                return ResourceManager.GetString("KEY_HOLE", resourceCulture);
            }
        }
        
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        internal static string CANDLE {
            get {
                return ResourceManager.GetString("CANDLE", resourceCulture);
            }
        }
        
        internal static string STOVE {
            get {
                return ResourceManager.GetString("STOVE", resourceCulture);
            }
        }
        
        internal static string PILE_OF_WOOD {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD", resourceCulture);
            }
        }
        
        internal static string LIVINGROOM_WINDOW {
            get {
                return ResourceManager.GetString("LIVINGROOM_WINDOW", resourceCulture);
            }
        }
        
        internal static string WALL {
            get {
                return ResourceManager.GetString("WALL", resourceCulture);
            }
        }
        
        internal static string FLOOR {
            get {
                return ResourceManager.GetString("FLOOR", resourceCulture);
            }
        }
        
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        internal static string SHUTTER {
            get {
                return ResourceManager.GetString("SHUTTER", resourceCulture);
            }
        }
        
        internal static string INSPECTION_WINDOW {
            get {
                return ResourceManager.GetString("INSPECTION_WINDOW", resourceCulture);
            }
        }
        
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        internal static string SAUSAGE {
            get {
                return ResourceManager.GetString("SAUSAGE", resourceCulture);
            }
        }
        
        internal static string CHEST_LOCK {
            get {
                return ResourceManager.GetString("CHEST_LOCK", resourceCulture);
            }
        }
        
        internal static string KEY_HOLE_SHIELD {
            get {
                return ResourceManager.GetString("KEY_HOLE_SHIELD", resourceCulture);
            }
        }
        
        internal static string COMBUSTION_CHAMBER {
            get {
                return ResourceManager.GetString("COMBUSTION_CHAMBER", resourceCulture);
            }
        }
        
        internal static string BOOKSHELF {
            get {
                return ResourceManager.GetString("BOOKSHELF", resourceCulture);
            }
        }
        
        internal static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        internal static string LAMP_OIL_BUCKET {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET", resourceCulture);
            }
        }
        
        internal static string PETROLEUM {
            get {
                return ResourceManager.GetString("PETROLEUM", resourceCulture);
            }
        }
        
        internal static string CHIMNEY {
            get {
                return ResourceManager.GetString("CHIMNEY", resourceCulture);
            }
        }
        
        internal static string COOKTOP {
            get {
                return ResourceManager.GetString("COOKTOP", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP", resourceCulture);
            }
        }
        
        internal static string WOODEN_KEY {
            get {
                return ResourceManager.GetString("WOODEN_KEY", resourceCulture);
            }
        }
        
        internal static string RUSTY_KEY {
            get {
                return ResourceManager.GetString("RUSTY_KEY", resourceCulture);
            }
        }
    }
}
