//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.TestGame.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.TestGame.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LIVINGROOM {
            get {
                return ResourceManager.GetString("LIVINGROOM", resourceCulture);
            }
        }
        
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        internal static string CLOSING {
            get {
                return ResourceManager.GetString("CLOSING", resourceCulture);
            }
        }
        
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        internal static string CHEST {
            get {
                return ResourceManager.GetString("CHEST", resourceCulture);
            }
        }
        
        internal static string PLANK {
            get {
                return ResourceManager.GetString("PLANK", resourceCulture);
            }
        }
        
        internal static string CHEST_LOCKED {
            get {
                return ResourceManager.GetString("CHEST_LOCKED", resourceCulture);
            }
        }
        
        internal static string DOOR {
            get {
                return ResourceManager.GetString("DOOR", resourceCulture);
            }
        }
        
        internal static string DOOR_FIRSTLOOK {
            get {
                return ResourceManager.GetString("DOOR_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string BEDROOM {
            get {
                return ResourceManager.GetString("BEDROOM", resourceCulture);
            }
        }
        
        internal static string CELLAR {
            get {
                return ResourceManager.GetString("CELLAR", resourceCulture);
            }
        }
        
        internal static string ATTIC {
            get {
                return ResourceManager.GetString("ATTIC", resourceCulture);
            }
        }
        
        internal static string FREEDOM {
            get {
                return ResourceManager.GetString("FREEDOM", resourceCulture);
            }
        }
        
        internal static string KEY_HOLE {
            get {
                return ResourceManager.GetString("KEY_HOLE", resourceCulture);
            }
        }
        
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        internal static string CANDLE {
            get {
                return ResourceManager.GetString("CANDLE", resourceCulture);
            }
        }
        
        internal static string CANDLE_CONTAINMENT {
            get {
                return ResourceManager.GetString("CANDLE_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string CANT_LEAVE_ROOM_WITHOUT_LIGHT {
            get {
                return ResourceManager.GetString("CANT_LEAVE_ROOM_WITHOUT_LIGHT", resourceCulture);
            }
        }
        
        internal static string STOVE {
            get {
                return ResourceManager.GetString("STOVE", resourceCulture);
            }
        }
        
        internal static string STOVE_FIRSTLOOK {
            get {
                return ResourceManager.GetString("STOVE_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string CANDLE_PICKUP {
            get {
                return ResourceManager.GetString("CANDLE_PICKUP", resourceCulture);
            }
        }
        
        internal static string STOVE_CLOSED {
            get {
                return ResourceManager.GetString("STOVE_CLOSED", resourceCulture);
            }
        }
        
        internal static string STOVE_MUST_BE_OPEN {
            get {
                return ResourceManager.GetString("STOVE_MUST_BE_OPEN", resourceCulture);
            }
        }
        
        internal static string PILE_OF_WOOD {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD", resourceCulture);
            }
        }
        
        internal static string LIVINGROOM_WINDOW {
            get {
                return ResourceManager.GetString("LIVINGROOM_WINDOW", resourceCulture);
            }
        }
        
        internal static string WALL {
            get {
                return ResourceManager.GetString("WALL", resourceCulture);
            }
        }
        
        internal static string FLOOR {
            get {
                return ResourceManager.GetString("FLOOR", resourceCulture);
            }
        }
        
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        internal static string IRON_KEY {
            get {
                return ResourceManager.GetString("IRON_KEY", resourceCulture);
            }
        }
        
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        internal static string NOTE_LETTER_CONTENT {
            get {
                return ResourceManager.GetString("NOTE_LETTER_CONTENT", resourceCulture);
            }
        }
        
        internal static string SHUTTER {
            get {
                return ResourceManager.GetString("SHUTTER", resourceCulture);
            }
        }
        
        internal static string INSPECTION_WINDOW {
            get {
                return ResourceManager.GetString("INSPECTION_WINDOW", resourceCulture);
            }
        }
        
        internal static string STOVE_CONTAINMENT {
            get {
                return ResourceManager.GetString("STOVE_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        internal static string KITCHEN_CABINET_CONTAINMENT {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string SAUSAGE {
            get {
                return ResourceManager.GetString("SAUSAGE", resourceCulture);
            }
        }
        
        internal static string SAUSAGE_CONTAINMENT {
            get {
                return ResourceManager.GetString("SAUSAGE_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string CHEST_LOCK {
            get {
                return ResourceManager.GetString("CHEST_LOCK", resourceCulture);
            }
        }
        
        internal static string KEY_HOLE_SHIELD {
            get {
                return ResourceManager.GetString("KEY_HOLE_SHIELD", resourceCulture);
            }
        }
        
        internal static string COMBUSTION_CHAMBER {
            get {
                return ResourceManager.GetString("COMBUSTION_CHAMBER", resourceCulture);
            }
        }
        
        internal static string STOVE_OPEN {
            get {
                return ResourceManager.GetString("STOVE_OPEN", resourceCulture);
            }
        }
        
        internal static string BOOKSHELF {
            get {
                return ResourceManager.GetString("BOOKSHELF", resourceCulture);
            }
        }
        
        internal static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        internal static string BOOK_I {
            get {
                return ResourceManager.GetString("BOOK_I", resourceCulture);
            }
        }
        
        internal static string BOOK_II {
            get {
                return ResourceManager.GetString("BOOK_II", resourceCulture);
            }
        }
        
        internal static string BOOK_III {
            get {
                return ResourceManager.GetString("BOOK_III", resourceCulture);
            }
        }
        
        internal static string BOOK_IV {
            get {
                return ResourceManager.GetString("BOOK_IV", resourceCulture);
            }
        }
        
        internal static string BOOK_V {
            get {
                return ResourceManager.GetString("BOOK_V", resourceCulture);
            }
        }
        
        internal static string LAMP_OIL_BUCKET {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET", resourceCulture);
            }
        }
        
        internal static string LAMP_OIL_BUCKET_CONTAINMENT {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string PETROLEUM {
            get {
                return ResourceManager.GetString("PETROLEUM", resourceCulture);
            }
        }
        
        internal static string CANT_DROP_CANDLE_IN_STOVE {
            get {
                return ResourceManager.GetString("CANT_DROP_CANDLE_IN_STOVE", resourceCulture);
            }
        }
        
        internal static string NO_FIRE_ACCELERATOR {
            get {
                return ResourceManager.GetString("NO_FIRE_ACCELERATOR", resourceCulture);
            }
        }
        
        internal static string NOTE_BURNED {
            get {
                return ResourceManager.GetString("NOTE_BURNED", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_BURNED {
            get {
                return ResourceManager.GetString("PETROLEUM_BURNED", resourceCulture);
            }
        }
        
        internal static string FIRE_STARTER {
            get {
                return ResourceManager.GetString("FIRE_STARTER", resourceCulture);
            }
        }
        
        internal static string CANT_OPEN_STOVE_ON_FIRE {
            get {
                return ResourceManager.GetString("CANT_OPEN_STOVE_ON_FIRE", resourceCulture);
            }
        }
        
        internal static string CHIMNEY {
            get {
                return ResourceManager.GetString("CHIMNEY", resourceCulture);
            }
        }
        
        internal static string COOKTOP {
            get {
                return ResourceManager.GetString("COOKTOP", resourceCulture);
            }
        }
        
        internal static string COOCKTOP_LINKEDTO {
            get {
                return ResourceManager.GetString("COOCKTOP_LINKEDTO", resourceCulture);
            }
        }
        
        internal static string LIVINGROOM_WAIT {
            get {
                return ResourceManager.GetString("LIVINGROOM_WAIT", resourceCulture);
            }
        }
        
        internal static string CANT_TAKE_PETROLEUM {
            get {
                return ResourceManager.GetString("CANT_TAKE_PETROLEUM", resourceCulture);
            }
        }
        
        internal static string LAMP_OIL_BUCKET_FIRSTLOOK {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string PILE_OF_WOOD_WITH_PETROLEUM {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD_WITH_PETROLEUM", resourceCulture);
            }
        }
        
        internal static string NOTHING_TO_HOLD {
            get {
                return ResourceManager.GetString("NOTHING_TO_HOLD", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_IN_STOVE {
            get {
                return ResourceManager.GetString("PETROLEUM_IN_STOVE", resourceCulture);
            }
        }
        
        internal static string PAPER_IN_STOVE {
            get {
                return ResourceManager.GetString("PAPER_IN_STOVE", resourceCulture);
            }
        }
        
        internal static string POOR_PETROLEUM_OVER_WOOD {
            get {
                return ResourceManager.GetString("POOR_PETROLEUM_OVER_WOOD", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP_FIRSTLOOK {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string BURN_NOTE {
            get {
                return ResourceManager.GetString("BURN_NOTE", resourceCulture);
            }
        }
        
        internal static string ENOUGH_PETROLEUM_IN_LAMP {
            get {
                return ResourceManager.GetString("ENOUGH_PETROLEUM_IN_LAMP", resourceCulture);
            }
        }
        
        internal static string POOR_PETROLEUM_IN_LAMP {
            get {
                return ResourceManager.GetString("POOR_PETROLEUM_IN_LAMP", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP_NOT_BURNING {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_NOT_BURNING", resourceCulture);
            }
        }
        
        internal static string NO_PETROLEUM_IN_LAMP {
            get {
                return ResourceManager.GetString("NO_PETROLEUM_IN_LAMP", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP_IS_BURNING {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_IS_BURNING", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP_SWITCH_ON {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_SWITCH_ON", resourceCulture);
            }
        }
        
        internal static string LIGHTER_ON {
            get {
                return ResourceManager.GetString("LIGHTER_ON", resourceCulture);
            }
        }
        
        internal static string LIGHTER_OFF {
            get {
                return ResourceManager.GetString("LIGHTER_OFF", resourceCulture);
            }
        }
        
        internal static string PETROLEUM_LAMP_FIRSTLOOK_POORED {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_FIRSTLOOK_POORED", resourceCulture);
            }
        }
        
        internal static string FREEDOM_DESTINATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREEDOM_DESTINATION_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string FREEDOM_LOCK_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREEDOM_LOCK_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string HOW_TO_DO {
            get {
                return ResourceManager.GetString("HOW_TO_DO", resourceCulture);
            }
        }
        
        internal static string FIRE_FIRE_WITH_FIRE {
            get {
                return ResourceManager.GetString("FIRE_FIRE_WITH_FIRE", resourceCulture);
            }
        }
        
        internal static string MELT_CANDLE_I {
            get {
                return ResourceManager.GetString("MELT_CANDLE_I", resourceCulture);
            }
        }
        
        internal static string MELT_CANDLE_II {
            get {
                return ResourceManager.GetString("MELT_CANDLE_II", resourceCulture);
            }
        }
        
        internal static string MELT_CANDLE_III {
            get {
                return ResourceManager.GetString("MELT_CANDLE_III", resourceCulture);
            }
        }
        
        internal static string CENTRAL_MESSAGE_UNDERSTOOD {
            get {
                return ResourceManager.GetString("CENTRAL_MESSAGE_UNDERSTOOD", resourceCulture);
            }
        }
        
        internal static string BOOKSHELF_CONTAINMENT {
            get {
                return ResourceManager.GetString("BOOKSHELF_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string WOODEN_KEY {
            get {
                return ResourceManager.GetString("WOODEN_KEY", resourceCulture);
            }
        }
        
        internal static string RUSTY_KEY {
            get {
                return ResourceManager.GetString("RUSTY_KEY", resourceCulture);
            }
        }
        
        internal static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
    }
}
