//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.TestGame.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.TestGame.Resources.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LIVINGROOM {
            get {
                return ResourceManager.GetString("LIVINGROOM", resourceCulture);
            }
        }
        
        internal static string BEDROOM {
            get {
                return ResourceManager.GetString("BEDROOM", resourceCulture);
            }
        }
        
        internal static string CELLAR {
            get {
                return ResourceManager.GetString("CELLAR", resourceCulture);
            }
        }
        
        internal static string ATTIC {
            get {
                return ResourceManager.GetString("ATTIC", resourceCulture);
            }
        }
        
        internal static string FREEDOM {
            get {
                return ResourceManager.GetString("FREEDOM", resourceCulture);
            }
        }
    }
}
