//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.BaseDescriptions", typeof(BaseDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du trägst im Moment Gegenstände mit einem Gesamtgewicht von {0, 0:F3} kg. Du kannst noch {1, 0:F3} kg zusätzlich tragen..
        /// </summary>
        public static string ACTUAL_PAYLOAD {
            get {
                return ResourceManager.GetString("ACTUAL_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erreichte Wertung {0}/{1}.
        /// </summary>
        public static string ACTUAL_SCORE {
            get {
                return ResourceManager.GetString("ACTUAL_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits zerbrochen..
        /// </summary>
        public static string ALREADY_BROKEN {
            get {
                return ResourceManager.GetString("ALREADY_BROKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steig zunächst von Deiner aktuellen Position herab..
        /// </summary>
        public static string ALREADY_CLIMBED {
            get {
                return ResourceManager.GetString("ALREADY_CLIMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist doch schon auf {0} gestiegen..
        /// </summary>
        public static string ALREADY_CLIMBED_ITEM {
            get {
                return ResourceManager.GetString("ALREADY_CLIMBED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits geschlossen..
        /// </summary>
        public static string ALREADY_CLOSED {
            get {
                return ResourceManager.GetString("ALREADY_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits abgeschlossen..
        /// </summary>
        public static string ALREADY_LOCKED {
            get {
                return ResourceManager.GetString("ALREADY_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits geöffnet..
        /// </summary>
        public static string ALREADY_OPEN {
            get {
                return ResourceManager.GetString("ALREADY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stehe zunächst von Deiner aktuellen Position wieder auf..
        /// </summary>
        public static string ALREADY_SITTING {
            get {
                return ResourceManager.GetString("ALREADY_SITTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits ausgeschaltet..
        /// </summary>
        public static string ALREADY_SWITCHEDOFF {
            get {
                return ResourceManager.GetString("ALREADY_SWITCHEDOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits angeschaltet..
        /// </summary>
        public static string ALREADY_SWITCHEDON {
            get {
                return ResourceManager.GetString("ALREADY_SWITCHEDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits entriegelt..
        /// </summary>
        public static string ALREADY_UNLOCKED {
            get {
                return ResourceManager.GetString("ALREADY_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du scheinst {0} schon zu tragen..
        /// </summary>
        public static string ALREADY_WEARING {
            get {
                return ResourceManager.GetString("ALREADY_WEARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Bezeichnungen für Personen und Gegenstände.
        /// </summary>
        public static string ALTER_EGO {
            get {
                return ResourceManager.GetString("ALTER_EGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Begriffe kannst Du für &apos;{0}&apos; ebenfalls benutzen: .
        /// </summary>
        public static string ALTER_EGO_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALTER_EGO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, scheinbar gibt es hier mehrere Objekte des selben Typs. Könntest Du etwas genauer beschreiben, was Du meinst?.
        /// </summary>
        public static string AMBIGUOUS_HERETICOBJECT {
            get {
                return ResourceManager.GetString("AMBIGUOUS_HERETICOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, scheinbar gibt es hier mehrere Orte mit einer ähnlichen Bezeichnung. Könntest Du etwas genauer beschreiben, welchen Ort Du meinst?.
        /// </summary>
        public static string AMBIGUOUS_LOCATION {
            get {
                return ResourceManager.GetString("AMBIGUOUS_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage eine Person.
        /// </summary>
        public static string ASK {
            get {
                return ResourceManager.GetString("ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dazu kann ich Ihnen im Moment nichts sagen&quot;, antwortet {0}..
        /// </summary>
        public static string ASK_FOR_INVISIBLE_OBJECT {
            get {
                return ResourceManager.GetString("ASK_FOR_INVISIBLE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  oder .
        /// </summary>
        public static string BINDING_OR {
            get {
                return ResourceManager.GetString("BINDING_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verhindern, dass Du weitere Gegenstände mitnehmen kannst..
        /// </summary>
        public static string BLOCK_PICKUP_PLURAL {
            get {
                return ResourceManager.GetString("BLOCK_PICKUP_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verhindert, dass Du weitere Gegenstände mitnehmen kannst..
        /// </summary>
        public static string BLOCK_PICKUP_SINGLE {
            get {
                return ResourceManager.GetString("BLOCK_PICKUP_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zerbrich, bzw. zerstöre einen Gegenstand.
        /// </summary>
        public static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufe einen Gegenstand.
        /// </summary>
        public static string BUY {
            get {
                return ResourceManager.GetString("BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht öffnen, während Du noch darauf sitzt..
        /// </summary>
        public static string CANT_OPEN_ITEM_WHILE_SITTING_ON_IT {
            get {
                return ResourceManager.GetString("CANT_OPEN_ITEM_WHILE_SITTING_ON_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht öffnen, während Du Dich noch darauf befindest..
        /// </summary>
        public static string CANT_OPEN_ITEM_WHILE_STANDING_ON_IT {
            get {
                return ResourceManager.GetString("CANT_OPEN_ITEM_WHILE_STANDING_ON_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht ausschalten..
        /// </summary>
        public static string CANT_SWITCHOFF_ITEM {
            get {
                return ResourceManager.GetString("CANT_SWITCHOFF_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst das Licht {0} nicht löschen..
        /// </summary>
        public static string CANT_SWITCHOFF_LIGHTER {
            get {
                return ResourceManager.GetString("CANT_SWITCHOFF_LIGHTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst Dich nicht selbst benutzen..
        /// </summary>
        public static string CANT_USE_YOURSELF {
            get {
                return ResourceManager.GetString("CANT_USE_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Benutze das Kommando &apos;ich bin ...&apos;, um Dir im Spiel einen Namen zu geben. &gt;&gt;.
        /// </summary>
        public static string CHANGE_NAME {
            get {
                return ResourceManager.GetString("CHANGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Person sehe ich hier nicht..
        /// </summary>
        public static string CHARACTER_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("CHARACTER_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klettere, bzw. steige auf ein Objekt..
        /// </summary>
        public static string CLIMB {
            get {
                return ResourceManager.GetString("CLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließe einen Gegenstand.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindet zwei Gegenstände miteinander..
        /// </summary>
        public static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zum Spiel abrufen.
        /// </summary>
        public static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zerschneide einen Gegenstand, bzw. schneide einen Gegenstand auf.
        /// </summary>
        public static string CUT {
            get {
                return ResourceManager.GetString("CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steige von dem Objekt herab, auf das Du geklettert bist..
        /// </summary>
        public static string DESCEND {
            get {
                return ResourceManager.GetString("DESCEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist heruntergestiegen..
        /// </summary>
        public static string DESCENDING {
            get {
                return ResourceManager.GetString("DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennt zwei verbundene Gegenstände voneinander..
        /// </summary>
        public static string DISCONNECT {
            get {
                return ResourceManager.GetString("DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das scheint nicht zu funktionieren..
        /// </summary>
        public static string DOES_NOT_WORK {
            get {
                return ResourceManager.GetString("DOES_NOT_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist vielleicht etwas unhöflich einfach so an einer Person zu riechen..
        /// </summary>
        public static string DONT_SMELL_ON_PERSON {
            get {
                return ResourceManager.GetString("DONT_SMELL_ON_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Moment macht es keinen Sinn mit einem Gegenstand zu reden..
        /// </summary>
        public static string DONT_TALK_TO_ITEM {
            get {
                return ResourceManager.GetString("DONT_TALK_TO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist vielleicht etwas unhöflich einfach so an einer Person zu knabbern..
        /// </summary>
        public static string DONT_TASTE_A_PERSON {
            get {
                return ResourceManager.GetString("DONT_TASTE_A_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Runter&quot;.
        /// </summary>
        public static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trink etwas.
        /// </summary>
        public static string DRINK {
            get {
                return ResourceManager.GetString("DRINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasse einen Gegenstand fallen.
        /// </summary>
        public static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Osten&quot;.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iss etwas.
        /// </summary>
        public static string EAT {
            get {
                return ResourceManager.GetString("EAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; ...drücke eine Taste, um das Spiel zu beenden... &gt;&gt;.
        /// </summary>
        public static string END_THE_GAME {
            get {
                return ResourceManager.GetString("END_THE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebene Datei scheint nicht zu existieren..
        /// </summary>
        public static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized with Heretic.InteractiveFiction v{0}.
        /// </summary>
        public static string FRAMEWORK_VERSION {
            get {
                return ResourceManager.GetString("FRAMEWORK_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Spiel wurde gespeichert unter: {0}.
        /// </summary>
        public static string GAME_SAVED {
            get {
                return ResourceManager.GetString("GAME_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sie.
        /// </summary>
        public static string GENDER_FEMALE {
            get {
                return ResourceManager.GetString("GENDER_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er.
        /// </summary>
        public static string GENDER_MALE {
            get {
                return ResourceManager.GetString("GENDER_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string GENDER_UNKNOWN {
            get {
                return ResourceManager.GetString("GENDER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überreiche einen Gegenstand.
        /// </summary>
        public static string GIVE {
            get {
                return ResourceManager.GetString("GIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehe zu einem Ort.
        /// </summary>
        public static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {0},.
        /// </summary>
        public static string HELLO_NAME {
            get {
                return ResourceManager.GetString("HELLO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo Fremder,.
        /// </summary>
        public static string HELLO_STRANGER {
            get {
                return ResourceManager.GetString("HELLO_STRANGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige diese Hilfeseite.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Schreibe &apos;hilfe&apos;, um Hilfe zu erhalten. &gt;&gt;.
        /// </summary>
        public static string HELP_WANTED {
            get {
                return ResourceManager.GetString("HELP_WANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du siehst .
        /// </summary>
        public static string HERE {
            get {
                return ResourceManager.GetString("HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sind hier..
        /// </summary>
        public static string HERE_PLURAL {
            get {
                return ResourceManager.GetString("HERE_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist hier..
        /// </summary>
        public static string HERE_SINGLE {
            get {
                return ResourceManager.GetString("HERE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltet das kontextbasierte Tipp-System an oder aus..
        /// </summary>
        public static string HINT {
            get {
                return ResourceManager.GetString("HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für was genau möchtest Du einen Hinweis bekommen?.
        /// </summary>
        public static string HINT_FOR_WHAT {
            get {
                return ResourceManager.GetString("HINT_FOR_WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweise sind nicht aktiviert..
        /// </summary>
        public static string HINT_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("HINT_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für {0} gibt es keine weiteren Hinweise..
        /// </summary>
        public static string HINT_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("HINT_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Hinweise wurden deaktiviert..
        /// </summary>
        public static string HINT_OFF {
            get {
                return ResourceManager.GetString("HINT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Hinweise wurden aktiviert..
        /// </summary>
        public static string HINT_ON {
            get {
                return ResourceManager.GetString("HINT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste alle bisherigen Kommandos auf.
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie oder womit möchtest Du das anzünden?.
        /// </summary>
        public static string HOW_TO_KINDLE {
            get {
                return ResourceManager.GetString("HOW_TO_KINDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst das nicht zerstören..
        /// </summary>
        public static string IMPOSSIBLE_BREAK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du das denn zerstören? Hast Du vielleicht irgendein entsprechendes Werkzeug?.
        /// </summary>
        public static string IMPOSSIBLE_BREAK_ITEM {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_BREAK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaah, eine Entführung? Das ist bestimmt ein ganz tolle Idee....
        /// </summary>
        public static string IMPOSSIBLE_CHARACTER_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CHARACTER_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein, ich werde dort nicht heraufklettern..
        /// </summary>
        public static string IMPOSSIBLE_CLIMB {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nicht zum Öffnen oder Schließen geeignet..
        /// </summary>
        public static string IMPOSSIBLE_CLOSE {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht mit anderen Dingen verbunden werden..
        /// </summary>
        public static string IMPOSSIBLE_CONNECT {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht mit {1} zerschneiden..
        /// </summary>
        public static string IMPOSSIBLE_CUT {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du denn {0} zerschneiden?.
        /// </summary>
        public static string IMPOSSIBLE_CUT_WITHOUT_TOOL {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CUT_WITHOUT_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht fallen lassen. Ist es noch mit einem anderen Gegenstand verbunden?.
        /// </summary>
        public static string IMPOSSIBLE_DROP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du denn {0} abschliessen? Hast Du vielleicht irgendeinen passenden Schlüssel?.
        /// </summary>
        public static string IMPOSSIBLE_LOCK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar lässt sich das nicht öffnen..
        /// </summary>
        public static string IMPOSSIBLE_OPEN {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar lässt sich {0} nicht öffnen..
        /// </summary>
        public static string IMPOSSIBLE_OPEN_ITEM {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_OPEN_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh wirklich? Mal ganz realistisch. Das kannst Du nicht mitnehmen!|Ich glaube nicht, dass Du das gebrauchen kannst.|Nein, auf keinen Fall!|Ein Tipp: Du brauchst das nicht und deshalb lassen wir das liegen..
        /// </summary>
        public static string IMPOSSIBLE_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst das nicht mitnehmen..
        /// </summary>
        public static string IMPOSSIBLE_SINGLE_ITEM_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_SINGLE_ITEM_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du denn {0} aufschliessen? Hast Du vielleicht irgendeinen passenden Schlüssel?.
        /// </summary>
        public static string IMPOSSIBLE_UNLOCK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du das denn aufschliessen? Hast Du vielleicht irgendeinen passenden Schlüssel?.
        /// </summary>
        public static string IMPOSSIBLE_UNLOCK_SURROUNDINGS {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK_SURROUNDINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lässt sich ohne passenden Schlüssel oder einen schlüsselähnlichen Gegenstand nicht öffnen. {1} ist auf jeden Fall nicht passend..
        /// </summary>
        public static string IMPOSSIBLE_UNLOCK_WITH_WRONG_KEY {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK_WITH_WRONG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit kannst Du {0} nichts anhaben..
        /// </summary>
        public static string INAPPROPRIATE_TOOL {
            get {
                return ResourceManager.GetString("INAPPROPRIATE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib bitte einen Dateinamen an..
        /// </summary>
        public static string INSERT_FILENAME {
            get {
                return ResourceManager.GetString("INSERT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Deine mitgeführten Gegenstände.
        /// </summary>
        public static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei Dir trägst Du .
        /// </summary>
        public static string INVENTORY {
            get {
                return ResourceManager.GetString("INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei sich trägt {0} .
        /// </summary>
        public static string INVENTORY_TEMPLATE {
            get {
                return ResourceManager.GetString("INVENTORY_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hm? Kannst es sein, dass Du den Gegenstand schon besitzt?.
        /// </summary>
        public static string ITEM_ALREADY_OWNED {
            get {
                return ResourceManager.GetString("ITEM_ALREADY_OWNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist auf {0} gestiegen..
        /// </summary>
        public static string ITEM_CLIMBED {
            get {
                return ResourceManager.GetString("ITEM_CLIMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du nimmst an {0} keinen außergewöhnlichen Geruch wahr..
        /// </summary>
        public static string ITEM_DOES_NOT_SMELL {
            get {
                return ResourceManager.GetString("ITEM_DOES_NOT_SMELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du nimmst an {0} keinen außergewöhnlichen Geschmack wahr..
        /// </summary>
        public static string ITEM_DOES_NOT_TASTE {
            get {
                return ResourceManager.GetString("ITEM_DOES_NOT_TASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} fallen gelassen..
        /// </summary>
        public static string ITEM_DROP {
            get {
                return ResourceManager.GetString("ITEM_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} in {1} gelegt..
        /// </summary>
        public static string ITEM_DROP_INTO {
            get {
                return ResourceManager.GetString("ITEM_DROP_INTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} auf {1} gelegt..
        /// </summary>
        public static string ITEM_DROP_ONTO {
            get {
                return ResourceManager.GetString("ITEM_DROP_ONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} getrunken..
        /// </summary>
        public static string ITEM_DRUNK {
            get {
                return ResourceManager.GetString("ITEM_DRUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} gegessen..
        /// </summary>
        public static string ITEM_EATEN {
            get {
                return ResourceManager.GetString("ITEM_EATEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wurde abgeschlossen..
        /// </summary>
        public static string ITEM_LOCKED {
            get {
                return ResourceManager.GetString("ITEM_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kramst ein wenig in Deinen Sachen und findest {0}. Das könnte funktionieren! Du probierst es einfach aus und es klappt! {1} wurde abgeschlossen..
        /// </summary>
        public static string ITEM_LOCKED_WITH_KEY_FROM_INVENTORY {
            get {
                return ResourceManager.GetString("ITEM_LOCKED_WITH_KEY_FROM_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar ist {0} hier nicht zu sehen..
        /// </summary>
        public static string ITEM_NAME_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("ITEM_NAME_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann keine anderen Objekte beinhalten oder aufnehmen..
        /// </summary>
        public static string ITEM_NOT_A_CONTAINER {
            get {
                return ResourceManager.GetString("ITEM_NOT_A_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst nichts in {0} legen..
        /// </summary>
        public static string ITEM_NOT_A_DROPTARGET {
            get {
                return ResourceManager.GetString("ITEM_NOT_A_DROPTARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst nichts auf {0} abstellen..
        /// </summary>
        public static string ITEM_NOT_A_TARGET {
            get {
                return ResourceManager.GetString("ITEM_NOT_A_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun nicht mehr mit {1} verbunden..
        /// </summary>
        public static string ITEM_NOT_CONNECTED_TO {
            get {
                return ResourceManager.GetString("ITEM_NOT_CONNECTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nicht mit anderen Dingen verbunden..
        /// </summary>
        public static string ITEM_NOT_CONNECTED_TO_OTHER_ITEMS {
            get {
                return ResourceManager.GetString("ITEM_NOT_CONNECTED_TO_OTHER_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht auf- oder zugeschlossen werden..
        /// </summary>
        public static string ITEM_NOT_LOCKABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_LOCKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das geht nicht. Du hast den Gegenstand offensichtlich gar nicht bei Dir. Oder ist er noch in einem anderen Behälter?.
        /// </summary>
        public static string ITEM_NOT_OWNED {
            get {
                return ResourceManager.GetString("ITEM_NOT_OWNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} offensichtlich gar nicht bei Dir..
        /// </summary>
        public static string ITEM_NOT_OWNED_FORMATTED {
            get {
                return ResourceManager.GetString("ITEM_NOT_OWNED_FORMATTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist nicht möglich, sich auf {0} zu setzen..
        /// </summary>
        public static string ITEM_NOT_SEATABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_SEATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesen Gegenstand sehe ich hier nicht!.
        /// </summary>
        public static string ITEM_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das kannst Du nicht anziehen!.
        /// </summary>
        public static string ITEM_NOT_WEARABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_WEARABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} offensichtlich gar nicht angezogen..
        /// </summary>
        public static string ITEM_NOT_WEARN {
            get {
                return ResourceManager.GetString("ITEM_NOT_WEARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun mit {1} verbunden..
        /// </summary>
        public static string ITEM_NOW_CONNECTED_TO {
            get {
                return ResourceManager.GetString("ITEM_NOW_CONNECTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar gibt es in diesem Raum nur eine richtige Sitzmöglichkeit. Daher nimmst Du einfach auf {0} Platz..
        /// </summary>
        public static string ITEM_ONLY_SEAT {
            get {
                return ResourceManager.GetString("ITEM_ONLY_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} genommen..
        /// </summary>
        public static string ITEM_PICKUP {
            get {
                return ResourceManager.GetString("ITEM_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun auf {1}..
        /// </summary>
        public static string ITEM_PUTON {
            get {
                return ResourceManager.GetString("ITEM_PUTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast auf {0} Platz genommen..
        /// </summary>
        public static string ITEM_SEATED {
            get {
                return ResourceManager.GetString("ITEM_SEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist noch geschlossen..
        /// </summary>
        public static string ITEM_STILL_CLOSED {
            get {
                return ResourceManager.GetString("ITEM_STILL_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist aber abgeschlossen..
        /// </summary>
        public static string ITEM_STILL_LOCKED {
            get {
                return ResourceManager.GetString("ITEM_STILL_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} ausgeschaltet..
        /// </summary>
        public static string ITEM_SWITCHEDOFF {
            get {
                return ResourceManager.GetString("ITEM_SWITCHEDOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} angeschaltet..
        /// </summary>
        public static string ITEM_SWITCHEDON {
            get {
                return ResourceManager.GetString("ITEM_SWITCHEDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht zerbrochen werden..
        /// </summary>
        public static string ITEM_UNBREAKABLE {
            get {
                return ResourceManager.GetString("ITEM_UNBREAKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich kenne und sehe nichts was &quot;{0}&quot; sein könnte..
        /// </summary>
        public static string ITEM_UNKNOWN {
            get {
                return ResourceManager.GetString("ITEM_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wurde aufgeschlossen..
        /// </summary>
        public static string ITEM_UNLOCKED {
            get {
                return ResourceManager.GetString("ITEM_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kramst ein wenig in Deinen Sachen und findest {0}. Das könnte funktionieren! Du probierst es einfach aus und es klappt! {1} wurde aufgeschlossen..
        /// </summary>
        public static string ITEM_UNLOCKED_WITH_KEY_FROM_INVENTORY {
            get {
                return ResourceManager.GetString("ITEM_UNLOCKED_WITH_KEY_FROM_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Gegenstände sind bereits miteinander verbunden..
        /// </summary>
        public static string ITEMS_ALREADY_CONNECTED {
            get {
                return ResourceManager.GetString("ITEMS_ALREADY_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Gegenstände sind nicht miteinander verbunden..
        /// </summary>
        public static string ITEMS_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("ITEMS_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Springe hoch oder auf ein Objekt.
        /// </summary>
        public static string JUMP {
            get {
                return ResourceManager.GetString("JUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mir ist nicht klar, was Du hier als Schlüssel verwenden willst..
        /// </summary>
        public static string KEY_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("KEY_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbrenne, bzw. zünde einen Gegenstand an.
        /// </summary>
        public static string KINDLE {
            get {
                return ResourceManager.GetString("KINDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dort steht geschrieben: 
        ///&quot;{0}&quot;.
        /// </summary>
        public static string LETTER_CONTENT {
            get {
                return ResourceManager.GetString("LETTER_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist verbunden mit .
        /// </summary>
        public static string LINKED_TO {
            get {
                return ResourceManager.GetString("LINKED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lädt einen Spielstand aus einer Datei.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielstand wird geladen....
        /// </summary>
        public static string LOAD_GAME {
            get {
                return ResourceManager.GetString("LOAD_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verriegel einen Gegenstand.
        /// </summary>
        public static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaue Dir Örtlichkeiten, Personen oder Gegenstände an.
        /// </summary>
        public static string LOOK {
            get {
                return ResourceManager.GetString("LOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst momentan ein maximales Gewicht von {0, 0:F3} kg tragen..
        /// </summary>
        public static string MAX_PAYLOAD {
            get {
                return ResourceManager.GetString("MAX_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich verstehe Dich nicht! Was genau möchtest Du tun?.
        /// </summary>
        public static string MISCONCEPTION {
            get {
                return ResourceManager.GetString("MISCONCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf welche der Sitzgelegenheiten möchtest Du denn Platz nehmen? Das musst Du schon genauer bestimmen..
        /// </summary>
        public static string MORE_SEATS {
            get {
                return ResourceManager.GetString("MORE_SEATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Nord&quot;.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändere Deinen Spielernamen.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Nord-Ost&quot;.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du sagst &quot;{0}&quot;. Keine Reaktion!.
        /// </summary>
        public static string NO_ANSWER {
            get {
                return ResourceManager.GetString("NO_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensichtlich gibt es darüber nichts zu sagen..
        /// </summary>
        public static string NO_ANSWER_EXCEPTION {
            get {
                return ResourceManager.GetString("NO_ANSWER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du fragst: &quot;Was ist mit {0}?&quot; Keine Reaktion!.
        /// </summary>
        public static string NO_ANSWER_TO_QUESTION {
            get {
                return ResourceManager.GetString("NO_ANSWER_TO_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irgendwie passiert nichts. Hattest Du vielleicht etwas anderes vor?.
        /// </summary>
        public static string NO_EVENT {
            get {
                return ResourceManager.GetString("NO_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar gibt es dort nichts zu lesen..
        /// </summary>
        public static string NO_LETTER_CONTENT {
            get {
                return ResourceManager.GetString("NO_LETTER_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier gibt es scheinbar keine Sitzmöglichkeit. Also bleibst Du einfach stehen..
        /// </summary>
        public static string NO_SEAT {
            get {
                return ResourceManager.GetString("NO_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst dort nicht hingehen!.
        /// </summary>
        public static string NO_WAY {
            get {
                return ResourceManager.GetString("NO_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Moment gibt es hier keine sichtbaren Wege. Vielleicht musst Du nur genau schauen, oder jemanden danach fragen?.
        /// </summary>
        public static string NO_WAYS {
            get {
                return ResourceManager.GetString("NO_WAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist aktuell nirgendwo heraufgeklettert..
        /// </summary>
        public static string NOT_CLIMBED {
            get {
                return ResourceManager.GetString("NOT_CLIMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist aber gar nicht auf {0}..
        /// </summary>
        public static string NOT_CLIMBED_ON_ITEM {
            get {
                return ResourceManager.GetString("NOT_CLIMBED_ON_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So wie es aussieht, sitzt Du gerade gar nicht..
        /// </summary>
        public static string NOT_SITTING {
            get {
                return ResourceManager.GetString("NOT_SITTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du fühlst Dich nicht müde..
        /// </summary>
        public static string NOT_TIRED {
            get {
                return ResourceManager.GetString("NOT_TIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast aktuell keine Gegenstände bei Dir..
        /// </summary>
        public static string NOTHING {
            get {
                return ResourceManager.GetString("NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts passiert!.
        /// </summary>
        public static string NOTHING_HAPPENS {
            get {
                return ResourceManager.GetString("NOTHING_HAPPENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht trinken..
        /// </summary>
        public static string NOTHING_TO_DRINK {
            get {
                return ResourceManager.GetString("NOTHING_TO_DRINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht essen..
        /// </summary>
        public static string NOTHING_TO_EAT {
            get {
                return ResourceManager.GetString("NOTHING_TO_EAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da gibt es nichts zu lesen..
        /// </summary>
        public static string NOTHING_TO_READ {
            get {
                return ResourceManager.GetString("NOTHING_TO_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du nimmst keinen außergewöhnlichen Geruch wahr..
        /// </summary>
        public static string NOTHING_TO_SMELL {
            get {
                return ResourceManager.GetString("NOTHING_TO_SMELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht ausschalten..
        /// </summary>
        public static string NOTHING_TO_SWITCHOFF {
            get {
                return ResourceManager.GetString("NOTHING_TO_SWITCHOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht anschalten..
        /// </summary>
        public static string NOTHING_TO_SWITCHON {
            get {
                return ResourceManager.GetString("NOTHING_TO_SWITCHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt hier keine Gegenstände die Du mitnehmen kannst..
        /// </summary>
        public static string NOTHING_TO_TAKE {
            get {
                return ResourceManager.GetString("NOTHING_TO_TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du nimmst keinen außergewöhnlichen Geschmack wahr..
        /// </summary>
        public static string NOTHING_TO_TASTE {
            get {
                return ResourceManager.GetString("NOTHING_TO_TASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht anziehen..
        /// </summary>
        public static string NOTHING_TO_WEAR {
            get {
                return ResourceManager.GetString("NOTHING_TO_WEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun geschlossen..
        /// </summary>
        public static string NOW_CLOSED {
            get {
                return ResourceManager.GetString("NOW_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun geöffnet..
        /// </summary>
        public static string NOW_OPEN {
            get {
                return ResourceManager.GetString("NOW_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Nord-West&quot;.
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das macht keinen Sinn. Du kannst das nicht kaufen..
        /// </summary>
        public static string ON_BUY_EXCEPTION {
            get {
                return ResourceManager.GetString("ON_BUY_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Moment kannst Du nur einen angrenzenden Raum direkt betreten..
        /// </summary>
        public static string ONLY_DIRECT_WAY {
            get {
                return ResourceManager.GetString("ONLY_DIRECT_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne einen Gegenstand.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit willst Du das bezahlen?.
        /// </summary>
        public static string PAY_WITH_WHAT {
            get {
                return ResourceManager.GetString("PAY_WITH_WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} genommen und {1} angezogen..
        /// </summary>
        public static string PICK_AND_PULLON_WEARABLE {
            get {
                return ResourceManager.GetString("PICK_AND_PULLON_WEARABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst Dich nicht selbst essen..
        /// </summary>
        public static string PLAYER_NOT_EATABLE {
            get {
                return ResourceManager.GetString("PLAYER_NOT_EATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst Dich nicht selbst mitnehmen..
        /// </summary>
        public static string PLAYER_NOT_PICKABLE {
            get {
                return ResourceManager.GetString("PLAYER_NOT_PICKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehe an einem Gegenstand.
        /// </summary>
        public static string PULL {
            get {
                return ResourceManager.GetString("PULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du ziehst an {0}, aber es passiert nichts..
        /// </summary>
        public static string PULL_DOES_NOT_WORK {
            get {
                return ResourceManager.GetString("PULL_DOES_NOT_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} angezogen..
        /// </summary>
        public static string PULLON_WEARABLE {
            get {
                return ResourceManager.GetString("PULLON_WEARABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücke, bzw. schiebe oder stecke einen Gegenstand in etwas hinein.
        /// </summary>
        public static string PUSH {
            get {
                return ResourceManager.GetString("PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lege, bzw. stelle einen Gegenstand auf einen anderen.
        /// </summary>
        public static string PUTON {
            get {
                return ResourceManager.GetString("PUTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Glückwunsch! Du hast gerade die Quest &apos;{0}&apos; gelöst. &gt;&gt;.
        /// </summary>
        public static string QUEST_SOLVED {
            get {
                return ResourceManager.GetString("QUEST_SOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beende das Spiel.
        /// </summary>
        public static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spiel wird beendet..
        /// </summary>
        public static string QUIT_GAME {
            get {
                return ResourceManager.GetString("QUIT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lies, was auf einem Gegenstand geschrieben steht.
        /// </summary>
        public static string READ {
            get {
                return ResourceManager.GetString("READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügt dem internen Protokoll einen Kommentar hinzu..
        /// </summary>
        public static string REM {
            get {
                return ResourceManager.GetString("REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte das Spiel neu.
        /// </summary>
        public static string RESTART {
            get {
                return ResourceManager.GetString("RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spiel wird neu gestartet..
        /// </summary>
        public static string RESTART_GAME {
            get {
                return ResourceManager.GetString("RESTART_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mache den letzten Befehl rückgängig.
        /// </summary>
        public static string REVERT {
            get {
                return ResourceManager.GetString("REVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Kommando &apos;{0}&apos; wird rückgängig gemacht....
        /// </summary>
        public static string REVERT_COMMAND {
            get {
                return ResourceManager.GetString("REVERT_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Tür scheint verschlossen zu sein..
        /// </summary>
        public static string ROOM_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("ROOM_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Süden&quot;.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichert Deinen aktuellen Spielstand.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heretic_savedgame.txt.
        /// </summary>
        public static string SAVE_NAME {
            get {
                return ResourceManager.GetString("SAVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprich mit einer Person.
        /// </summary>
        public static string SAY {
            get {
                return ResourceManager.GetString("SAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeigt Dir den aktuellen Punktestand.
        /// </summary>
        public static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Süd-Ost&quot;.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte Dich auf eine Sitzgelegenheit.
        /// </summary>
        public static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du sitzt gerade auf {0}..
        /// </summary>
        public static string SITTING_ON {
            get {
                return ResourceManager.GetString("SITTING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lege Dich zum Schlafen auf eine entsprechende Schlafgelegenheit.
        /// </summary>
        public static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rieche an einem Gegenstand.
        /// </summary>
        public static string SMELL {
            get {
                return ResourceManager.GetString("SMELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist aufgestanden..
        /// </summary>
        public static string STANDING_UP {
            get {
                return ResourceManager.GetString("STANDING_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stehe von einer Sitzgelegenheit auf.
        /// </summary>
        public static string STANDUP {
            get {
                return ResourceManager.GetString("STANDUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; ...drücke eine Taste, um das Spiel zu starten... &gt;&gt;.
        /// </summary>
        public static string START_THE_GAME {
            get {
                return ResourceManager.GetString("START_THE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selbst wenn das ginge, macht das gerade keinen Sinn..
        /// </summary>
        public static string SURROUNDING_NOT_SEATABLE {
            get {
                return ResourceManager.GetString("SURROUNDING_NOT_SEATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Süd-West&quot;.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalte ein Gerät aus.
        /// </summary>
        public static string SWITCHOFF {
            get {
                return ResourceManager.GetString("SWITCHOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalte ein Gerät an.
        /// </summary>
        public static string SWITCHON {
            get {
                return ResourceManager.GetString("SWITCHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etwas ist schief gegangen. Bitte probiere es erneut oder starte das Programm neu..
        /// </summary>
        public static string SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm einen Gegenstand.
        /// </summary>
        public static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehe ein Kleidungsstück aus.
        /// </summary>
        public static string TAKEOFF {
            get {
                return ResourceManager.GetString("TAKEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} ausgezogen und trägst {1} nun bei Dir..
        /// </summary>
        public static string TAKEOFF_WEARABLE {
            get {
                return ResourceManager.GetString("TAKEOFF_WEARABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smalltalk mit einer Person.
        /// </summary>
        public static string TALK {
            get {
                return ResourceManager.GetString("TALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schmecke an einem Gegenstand.
        /// </summary>
        public static string TASTE {
            get {
                return ResourceManager.GetString("TASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirf einen Gegenstand.
        /// </summary>
        public static string THROW {
            get {
                return ResourceManager.GetString("THROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zeit vergeht..
        /// </summary>
        public static string TIME_GOES_BY {
            get {
                return ResourceManager.GetString("TIME_GOES_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Gegenstand ist zu schwer, um ihn noch zu tragen! Vielleicht benötigst Du eine größere Transportmöglichkeit, oder Du wirfst einige Sachen weg..
        /// </summary>
        public static string TO_HEAVY {
            get {
                return ResourceManager.GetString("TO_HEAVY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mir ist nicht klar, was Du hier als Werkzeug verwenden willst..
        /// </summary>
        public static string TOOL_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("TOOL_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drehe einen Gegenstand, bzw. schließe oder öffne einen Gegenstand durch drehen.
        /// </summary>
        public static string TURN {
            get {
                return ResourceManager.GetString("TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entriegel einen Gegenstand.
        /// </summary>
        public static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Hoch&quot;.
        /// </summary>
        public static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutze einen Gegenstand.
        /// </summary>
        public static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Westen&quot;.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warte einen Augenblick und tue ansonsten nichts.
        /// </summary>
        public static string WAIT {
            get {
                return ResourceManager.GetString("WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liegt in Richtung.
        /// </summary>
        public static string WAY {
            get {
                return ResourceManager.GetString("WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Weg scheint geschlossen zu sein. Musst Du vielleicht erst etwas öffnen?.
        /// </summary>
        public static string WAY_IS_CLOSED {
            get {
                return ResourceManager.GetString("WAY_IS_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Weg scheint versperrt zu sein. Vielleicht benötigst Du eine Art Schlüssel?.
        /// </summary>
        public static string WAY_IS_LOCKED {
            get {
                return ResourceManager.GetString("WAY_IS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige alle verfügbaren Wege.
        /// </summary>
        public static string WAYS {
            get {
                return ResourceManager.GetString("WAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehe ein Kleidungsstück an.
        /// </summary>
        public static string WEAR {
            get {
                return ResourceManager.GetString("WEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Dinge hast Du angezogen: .
        /// </summary>
        public static string WEARING_ITEMS {
            get {
                return ResourceManager.GetString("WEARING_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Hm?&quot;, ist die verwunderte Antwort..
        /// </summary>
        public static string WHAT {
            get {
                return ResourceManager.GetString("WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du kaufen?.
        /// </summary>
        public static string WHAT_TO_BUY {
            get {
                return ResourceManager.GetString("WHAT_TO_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worauf genau möchtest Du klettern?.
        /// </summary>
        public static string WHAT_TO_CLIMB {
            get {
                return ResourceManager.GetString("WHAT_TO_CLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du schliessen?.
        /// </summary>
        public static string WHAT_TO_CLOSE {
            get {
                return ResourceManager.GetString("WHAT_TO_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest Du miteinander verbinden?.
        /// </summary>
        public static string WHAT_TO_CONNECT {
            get {
                return ResourceManager.GetString("WHAT_TO_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest Du mit {0} verbinden?.
        /// </summary>
        public static string WHAT_TO_CONNECT_TO {
            get {
                return ResourceManager.GetString("WHAT_TO_CONNECT_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du schneiden?.
        /// </summary>
        public static string WHAT_TO_CUT {
            get {
                return ResourceManager.GetString("WHAT_TO_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest Du von einander trennen?.
        /// </summary>
        public static string WHAT_TO_DISCONNECT {
            get {
                return ResourceManager.GetString("WHAT_TO_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest Du von {0} trennen?.
        /// </summary>
        public static string WHAT_TO_DISCONNECT_FROM {
            get {
                return ResourceManager.GetString("WHAT_TO_DISCONNECT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du fallen lassen?.
        /// </summary>
        public static string WHAT_TO_DROP {
            get {
                return ResourceManager.GetString("WHAT_TO_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du essen?.
        /// </summary>
        public static string WHAT_TO_EAT {
            get {
                return ResourceManager.GetString("WHAT_TO_EAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worauf möchtest Du denn springen?.
        /// </summary>
        public static string WHAT_TO_JUMP {
            get {
                return ResourceManager.GetString("WHAT_TO_JUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du anzünden?.
        /// </summary>
        public static string WHAT_TO_KINDLE {
            get {
                return ResourceManager.GetString("WHAT_TO_KINDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du verschliessen?.
        /// </summary>
        public static string WHAT_TO_LOCK {
            get {
                return ResourceManager.GetString("WHAT_TO_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du öffnen?.
        /// </summary>
        public static string WHAT_TO_OPEN {
            get {
                return ResourceManager.GetString("WHAT_TO_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du ziehen?.
        /// </summary>
        public static string WHAT_TO_PULL {
            get {
                return ResourceManager.GetString("WHAT_TO_PULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du drücken?.
        /// </summary>
        public static string WHAT_TO_PUSH {
            get {
                return ResourceManager.GetString("WHAT_TO_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worauf genau möchtest Du etwas stellen?.
        /// </summary>
        public static string WHAT_TO_PUTON {
            get {
                return ResourceManager.GetString("WHAT_TO_PUTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du lesen?.
        /// </summary>
        public static string WHAT_TO_READ {
            get {
                return ResourceManager.GetString("WHAT_TO_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du ausschalten?.
        /// </summary>
        public static string WHAT_TO_SWITCHOFF {
            get {
                return ResourceManager.GetString("WHAT_TO_SWITCHOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du anschalten?.
        /// </summary>
        public static string WHAT_TO_SWITCHON {
            get {
                return ResourceManager.GetString("WHAT_TO_SWITCHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du ausziehen?.
        /// </summary>
        public static string WHAT_TO_TAKEOFF {
            get {
                return ResourceManager.GetString("WHAT_TO_TAKEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sag mir doch bitte, mit wem Du reden möchtest?.
        /// </summary>
        public static string WHAT_TO_TALK {
            get {
                return ResourceManager.GetString("WHAT_TO_TALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du schmecken?.
        /// </summary>
        public static string WHAT_TO_TASTE {
            get {
                return ResourceManager.GetString("WHAT_TO_TASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du drehen?.
        /// </summary>
        public static string WHAT_TO_TURN {
            get {
                return ResourceManager.GetString("WHAT_TO_TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du aufschliessen?.
        /// </summary>
        public static string WHAT_TO_UNLOCK {
            get {
                return ResourceManager.GetString("WHAT_TO_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie genau oder womit möchtest Du das tun?.
        /// </summary>
        public static string WHAT_TO_USE {
            get {
                return ResourceManager.GetString("WHAT_TO_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was genau möchtest Du anziehen?.
        /// </summary>
        public static string WHAT_TO_WEAR {
            get {
                return ResourceManager.GetString("WHAT_TO_WEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibe oder tippe etwas.
        /// </summary>
        public static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit wird Dir das nicht gelingen!.
        /// </summary>
        public static string WRONG_BREAK_ITEM {
            get {
                return ResourceManager.GetString("WRONG_BREAK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} damit nicht aufschließen. Vielleicht probierst Du besser einen anderen Schlüssel?.
        /// </summary>
        public static string WRONG_KEY {
            get {
                return ResourceManager.GetString("WRONG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} damit nicht zerbrechen. Vielleicht probierst Du besser ein anderes Werkzeug?.
        /// </summary>
        public static string WRONG_TOOL {
            get {
                return ResourceManager.GetString("WRONG_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast gerade Punkte bekommen!.
        /// </summary>
        public static string YOU_SCORED_I {
            get {
                return ResourceManager.GetString("YOU_SCORED_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du scheinst Fortschritte zu machen..
        /// </summary>
        public static string YOU_SCORED_II {
            get {
                return ResourceManager.GetString("YOU_SCORED_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist Deinem Ziel wieder einen Schritt näher gekommen..
        /// </summary>
        public static string YOU_SCORED_III {
            get {
                return ResourceManager.GetString("YOU_SCORED_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darin befinden sich:.
        /// </summary>
        public static string YOU_SEE {
            get {
                return ResourceManager.GetString("YOU_SEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sie trägt bei sich:.
        /// </summary>
        public static string YOU_SEE_FEMALE {
            get {
                return ResourceManager.GetString("YOU_SEE_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er trägt bei sich:.
        /// </summary>
        public static string YOU_SEE_MALE {
            get {
                return ResourceManager.GetString("YOU_SEE_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darin befindet sich:.
        /// </summary>
        public static string YOU_SEE_SINGULAR {
            get {
                return ResourceManager.GetString("YOU_SEE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darauf befinden sich:.
        /// </summary>
        public static string YOU_SEE_SURFACE {
            get {
                return ResourceManager.GetString("YOU_SEE_SURFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darauf befindet sich:.
        /// </summary>
        public static string YOU_SEE_SURFACE_SINGULAR {
            get {
                return ResourceManager.GetString("YOU_SEE_SURFACE_SINGULAR", resourceCulture);
            }
        }
    }
}
