//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseDescriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseDescriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.BaseDescriptions", typeof(BaseDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LINKED_TO {
            get {
                return ResourceManager.GetString("LINKED_TO", resourceCulture);
            }
        }
        
        public static string NOTHING_HAPPENS {
            get {
                return ResourceManager.GetString("NOTHING_HAPPENS", resourceCulture);
            }
        }
        
        public static string ON_BUY_EXCEPTION {
            get {
                return ResourceManager.GetString("ON_BUY_EXCEPTION", resourceCulture);
            }
        }
        
        public static string HERE_PLURAL {
            get {
                return ResourceManager.GetString("HERE_PLURAL", resourceCulture);
            }
        }
        
        public static string HERE_SINGLE {
            get {
                return ResourceManager.GetString("HERE_SINGLE", resourceCulture);
            }
        }
        
        public static string YOU_SEE {
            get {
                return ResourceManager.GetString("YOU_SEE", resourceCulture);
            }
        }
        
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        public static string ALTER_EGO_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALTER_EGO_DESCRIPTION", resourceCulture);
            }
        }
        
        public static string YOU_SEE_FEMALE {
            get {
                return ResourceManager.GetString("YOU_SEE_FEMALE", resourceCulture);
            }
        }
        
        public static string YOU_SEE_MALE {
            get {
                return ResourceManager.GetString("YOU_SEE_MALE", resourceCulture);
            }
        }
        
        public static string GENDER_FEMALE {
            get {
                return ResourceManager.GetString("GENDER_FEMALE", resourceCulture);
            }
        }
        
        public static string GENDER_UNKNOWN {
            get {
                return ResourceManager.GetString("GENDER_UNKNOWN", resourceCulture);
            }
        }
        
        public static string GENDER_MALE {
            get {
                return ResourceManager.GetString("GENDER_MALE", resourceCulture);
            }
        }
        
        public static string NO_ANSWER_EXCEPTION {
            get {
                return ResourceManager.GetString("NO_ANSWER_EXCEPTION", resourceCulture);
            }
        }
        
        public static string WAY {
            get {
                return ResourceManager.GetString("WAY", resourceCulture);
            }
        }
        
        public static string HELLO_NAME {
            get {
                return ResourceManager.GetString("HELLO_NAME", resourceCulture);
            }
        }
        
        public static string HELLO_STRANGER {
            get {
                return ResourceManager.GetString("HELLO_STRANGER", resourceCulture);
            }
        }
        
        public static string NOTHING {
            get {
                return ResourceManager.GetString("NOTHING", resourceCulture);
            }
        }
        
        public static string ACTUAL_PAYLOAD {
            get {
                return ResourceManager.GetString("ACTUAL_PAYLOAD", resourceCulture);
            }
        }
        
        public static string MAX_PAYLOAD {
            get {
                return ResourceManager.GetString("MAX_PAYLOAD", resourceCulture);
            }
        }
        
        public static string BLOCK_PICKUP_PLURAL {
            get {
                return ResourceManager.GetString("BLOCK_PICKUP_PLURAL", resourceCulture);
            }
        }
        
        public static string BLOCK_PICKUP_SINGLE {
            get {
                return ResourceManager.GetString("BLOCK_PICKUP_SINGLE", resourceCulture);
            }
        }
        
        public static string INVENTORY {
            get {
                return ResourceManager.GetString("INVENTORY", resourceCulture);
            }
        }
        
        public static string NO_WAY {
            get {
                return ResourceManager.GetString("NO_WAY", resourceCulture);
            }
        }
        
        public static string NO_WAYS {
            get {
                return ResourceManager.GetString("NO_WAYS", resourceCulture);
            }
        }
        
        public static string CHARACTER_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("CHARACTER_NOT_VISIBLE", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_VISIBLE", resourceCulture);
            }
        }
        
        public static string ROOM_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("ROOM_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        public static string INVENTORY_TEMPLATE {
            get {
                return ResourceManager.GetString("INVENTORY_TEMPLATE", resourceCulture);
            }
        }
        
        public static string ITEM_ALREADY_OWNED {
            get {
                return ResourceManager.GetString("ITEM_ALREADY_OWNED", resourceCulture);
            }
        }
        
        public static string ITEM_DROP {
            get {
                return ResourceManager.GetString("ITEM_DROP", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_LOCKABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_LOCKABLE", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_OWNED {
            get {
                return ResourceManager.GetString("ITEM_NOT_OWNED", resourceCulture);
            }
        }
        
        public static string ITEM_PICKUP {
            get {
                return ResourceManager.GetString("ITEM_PICKUP", resourceCulture);
            }
        }
        
        public static string ITEM_STILL_LOCKED {
            get {
                return ResourceManager.GetString("ITEM_STILL_LOCKED", resourceCulture);
            }
        }
        
        public static string ITEM_UNLOCKED {
            get {
                return ResourceManager.GetString("ITEM_UNLOCKED", resourceCulture);
            }
        }
        
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        public static string HELP_WANTED {
            get {
                return ResourceManager.GetString("HELP_WANTED", resourceCulture);
            }
        }
        
        public static string ALTER_EGO {
            get {
                return ResourceManager.GetString("ALTER_EGO", resourceCulture);
            }
        }
        
        public static string ASK {
            get {
                return ResourceManager.GetString("ASK", resourceCulture);
            }
        }
        
        public static string BUY {
            get {
                return ResourceManager.GetString("BUY", resourceCulture);
            }
        }
        
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        public static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        public static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        public static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        public static string GIVE {
            get {
                return ResourceManager.GetString("GIVE", resourceCulture);
            }
        }
        
        public static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        public static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        public static string JUMP {
            get {
                return ResourceManager.GetString("JUMP", resourceCulture);
            }
        }
        
        public static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        public static string LOOK {
            get {
                return ResourceManager.GetString("LOOK", resourceCulture);
            }
        }
        
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        public static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        public static string SAY {
            get {
                return ResourceManager.GetString("SAY", resourceCulture);
            }
        }
        
        public static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        public static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        public static string TALK {
            get {
                return ResourceManager.GetString("TALK", resourceCulture);
            }
        }
        
        public static string TURN {
            get {
                return ResourceManager.GetString("TURN", resourceCulture);
            }
        }
        
        public static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        public static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        public static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        public static string WAYS {
            get {
                return ResourceManager.GetString("WAYS", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_CHARACTER_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CHARACTER_PICKUP", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_DROP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_DROP", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_PICKUP", resourceCulture);
            }
        }
        
        public static string TO_HEAVY {
            get {
                return ResourceManager.GetString("TO_HEAVY", resourceCulture);
            }
        }
        
        public static string ALREADY_CLOSED {
            get {
                return ResourceManager.GetString("ALREADY_CLOSED", resourceCulture);
            }
        }
        
        public static string ALREADY_OPEN {
            get {
                return ResourceManager.GetString("ALREADY_OPEN", resourceCulture);
            }
        }
        
        public static string ALREADY_UNLOCKED {
            get {
                return ResourceManager.GetString("ALREADY_UNLOCKED", resourceCulture);
            }
        }
        
        public static string NOW_CLOSED {
            get {
                return ResourceManager.GetString("NOW_CLOSED", resourceCulture);
            }
        }
        
        public static string NOW_OPEN {
            get {
                return ResourceManager.GetString("NOW_OPEN", resourceCulture);
            }
        }
        
        public static string MISCONCEPTION {
            get {
                return ResourceManager.GetString("MISCONCEPTION", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_TAKE {
            get {
                return ResourceManager.GetString("NOTHING_TO_TAKE", resourceCulture);
            }
        }
        
        public static string NO_ANSWER {
            get {
                return ResourceManager.GetString("NO_ANSWER", resourceCulture);
            }
        }
        
        public static string NO_ANSWER_TO_QUESTION {
            get {
                return ResourceManager.GetString("NO_ANSWER_TO_QUESTION", resourceCulture);
            }
        }
        
        public static string WRONG_KEY {
            get {
                return ResourceManager.GetString("WRONG_KEY", resourceCulture);
            }
        }
        
        public static string SAME_ACTION_AGAIN {
            get {
                return ResourceManager.GetString("SAME_ACTION_AGAIN", resourceCulture);
            }
        }
        
        public static string NO_EVENT {
            get {
                return ResourceManager.GetString("NO_EVENT", resourceCulture);
            }
        }
        
        public static string WAY_IS_CLOSED {
            get {
                return ResourceManager.GetString("WAY_IS_CLOSED", resourceCulture);
            }
        }
        
        public static string WAY_IS_LOCKED {
            get {
                return ResourceManager.GetString("WAY_IS_LOCKED", resourceCulture);
            }
        }
        
        public static string ITEM_UNKNOWN {
            get {
                return ResourceManager.GetString("ITEM_UNKNOWN", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_UNLOCK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK", resourceCulture);
            }
        }
        
        public static string WHAT {
            get {
                return ResourceManager.GetString("WHAT", resourceCulture);
            }
        }
        
        public static string PAY_WITH_WHAT {
            get {
                return ResourceManager.GetString("PAY_WITH_WHAT", resourceCulture);
            }
        }
        
        public static string ASK_FOR_INVISIBLE_OBJECT {
            get {
                return ResourceManager.GetString("ASK_FOR_INVISIBLE_OBJECT", resourceCulture);
            }
        }
        
        public static string ITEM_EATEN {
            get {
                return ResourceManager.GetString("ITEM_EATEN", resourceCulture);
            }
        }
        
        public static string START_THE_GAME {
            get {
                return ResourceManager.GetString("START_THE_GAME", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_UNLOCK_SURROUNDINGS {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK_SURROUNDINGS", resourceCulture);
            }
        }
        
        public static string KEY_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("KEY_NOT_VISIBLE", resourceCulture);
            }
        }
        
        public static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        public static string ITEM_SEATED {
            get {
                return ResourceManager.GetString("ITEM_SEATED", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_SEATABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_SEATABLE", resourceCulture);
            }
        }
        
        public static string SURROUNDING_NOT_SEATABLE {
            get {
                return ResourceManager.GetString("SURROUNDING_NOT_SEATABLE", resourceCulture);
            }
        }
        
        public static string STANDING_UP {
            get {
                return ResourceManager.GetString("STANDING_UP", resourceCulture);
            }
        }
        
        public static string NOT_SITTING {
            get {
                return ResourceManager.GetString("NOT_SITTING", resourceCulture);
            }
        }
        
        public static string STANDUP {
            get {
                return ResourceManager.GetString("STANDUP", resourceCulture);
            }
        }
        
        public static string SITTING_ON {
            get {
                return ResourceManager.GetString("SITTING_ON", resourceCulture);
            }
        }
        
        public static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
        
        public static string ITEM_ONLY_SEAT {
            get {
                return ResourceManager.GetString("ITEM_ONLY_SEAT", resourceCulture);
            }
        }
        
        public static string NO_SEAT {
            get {
                return ResourceManager.GetString("NO_SEAT", resourceCulture);
            }
        }
        
        public static string MORE_SEATS {
            get {
                return ResourceManager.GetString("MORE_SEATS", resourceCulture);
            }
        }
        
        public static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_BREAK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_BREAK", resourceCulture);
            }
        }
        
        public static string ALREADY_BROKEN {
            get {
                return ResourceManager.GetString("ALREADY_BROKEN", resourceCulture);
            }
        }
        
        public static string ITEM_UNBREAKABLE {
            get {
                return ResourceManager.GetString("ITEM_UNBREAKABLE", resourceCulture);
            }
        }
        
        public static string WRONG_TOOL {
            get {
                return ResourceManager.GetString("WRONG_TOOL", resourceCulture);
            }
        }
        
        public static string TOOL_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("TOOL_NOT_VISIBLE", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_OPEN {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_OPEN", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_BREAK_ITEM {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_BREAK_ITEM", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_UNLOCK_WITH_WRONG_KEY {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK_WITH_WRONG_KEY", resourceCulture);
            }
        }
        
        public static string PULL {
            get {
                return ResourceManager.GetString("PULL", resourceCulture);
            }
        }
        
        public static string WRONG_BREAK_ITEM {
            get {
                return ResourceManager.GetString("WRONG_BREAK_ITEM", resourceCulture);
            }
        }
        
        public static string PUSH {
            get {
                return ResourceManager.GetString("PUSH", resourceCulture);
            }
        }
        
        public static string DOES_NOT_WORK {
            get {
                return ResourceManager.GetString("DOES_NOT_WORK", resourceCulture);
            }
        }
        
        public static string WEARING_ITEMS {
            get {
                return ResourceManager.GetString("WEARING_ITEMS", resourceCulture);
            }
        }
        
        public static string CLIMB {
            get {
                return ResourceManager.GetString("CLIMB", resourceCulture);
            }
        }
        
        public static string ALREADY_CLIMBED {
            get {
                return ResourceManager.GetString("ALREADY_CLIMBED", resourceCulture);
            }
        }
        
        public static string ITEM_CLIMBED {
            get {
                return ResourceManager.GetString("ITEM_CLIMBED", resourceCulture);
            }
        }
        
        public static string DESCENDING {
            get {
                return ResourceManager.GetString("DESCENDING", resourceCulture);
            }
        }
        
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        public static string GAME_SAVED {
            get {
                return ResourceManager.GetString("GAME_SAVED", resourceCulture);
            }
        }
        
        public static string SAVE_NAME {
            get {
                return ResourceManager.GetString("SAVE_NAME", resourceCulture);
            }
        }
        
        public static string DESCEND {
            get {
                return ResourceManager.GetString("DESCEND", resourceCulture);
            }
        }
        
        public static string QUEST_SOLVED {
            get {
                return ResourceManager.GetString("QUEST_SOLVED", resourceCulture);
            }
        }
        
        public static string QUIT_GAME {
            get {
                return ResourceManager.GetString("QUIT_GAME", resourceCulture);
            }
        }
        
        public static string HINT {
            get {
                return ResourceManager.GetString("HINT", resourceCulture);
            }
        }
        
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        public static string HINT_ON {
            get {
                return ResourceManager.GetString("HINT_ON", resourceCulture);
            }
        }
        
        public static string HINT_OFF {
            get {
                return ResourceManager.GetString("HINT_OFF", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_SINGLE_ITEM_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_SINGLE_ITEM_PICKUP", resourceCulture);
            }
        }
        
        public static string REM {
            get {
                return ResourceManager.GetString("REM", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_CLIMB {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CLIMB", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_CLOSE {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CLOSE", resourceCulture);
            }
        }
        
        public static string YOU_SEE_SINGULAR {
            get {
                return ResourceManager.GetString("YOU_SEE_SINGULAR", resourceCulture);
            }
        }
        
        public static string CHANGE_NAME {
            get {
                return ResourceManager.GetString("CHANGE_NAME", resourceCulture);
            }
        }
        
        public static string HERE {
            get {
                return ResourceManager.GetString("HERE", resourceCulture);
            }
        }
        
        public static string FRAMEWORK_VERSION {
            get {
                return ResourceManager.GetString("FRAMEWORK_VERSION", resourceCulture);
            }
        }
        
        public static string ALREADY_SITTING {
            get {
                return ResourceManager.GetString("ALREADY_SITTING", resourceCulture);
            }
        }
        
        public static string END_THE_GAME {
            get {
                return ResourceManager.GetString("END_THE_GAME", resourceCulture);
            }
        }
        
        public static string ITEM_STILL_CLOSED {
            get {
                return ResourceManager.GetString("ITEM_STILL_CLOSED", resourceCulture);
            }
        }
        
        public static string ITEM_DROP_INTO {
            get {
                return ResourceManager.GetString("ITEM_DROP_INTO", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_A_CONTAINER {
            get {
                return ResourceManager.GetString("ITEM_NOT_A_CONTAINER", resourceCulture);
            }
        }
        
        public static string YOU_SEE_SURFACE {
            get {
                return ResourceManager.GetString("YOU_SEE_SURFACE", resourceCulture);
            }
        }
        
        public static string YOU_SEE_SURFACE_SINGULAR {
            get {
                return ResourceManager.GetString("YOU_SEE_SURFACE_SINGULAR", resourceCulture);
            }
        }
        
        public static string LETTER_CONTENT {
            get {
                return ResourceManager.GetString("LETTER_CONTENT", resourceCulture);
            }
        }
        
        public static string NO_LETTER_CONTENT {
            get {
                return ResourceManager.GetString("NO_LETTER_CONTENT", resourceCulture);
            }
        }
        
        public static string ITEM_DROP_ONTO {
            get {
                return ResourceManager.GetString("ITEM_DROP_ONTO", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_READ {
            get {
                return ResourceManager.GetString("NOTHING_TO_READ", resourceCulture);
            }
        }
        
        public static string INAPPROPRIATE_TOOL {
            get {
                return ResourceManager.GetString("INAPPROPRIATE_TOOL", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_OPEN_ITEM {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_OPEN_ITEM", resourceCulture);
            }
        }
        
        public static string TIME_GOES_BY {
            get {
                return ResourceManager.GetString("TIME_GOES_BY", resourceCulture);
            }
        }
        
        public static string WAIT {
            get {
                return ResourceManager.GetString("WAIT", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_OWNED_FORMATTED {
            get {
                return ResourceManager.GetString("ITEM_NOT_OWNED_FORMATTED", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_EAT {
            get {
                return ResourceManager.GetString("NOTHING_TO_EAT", resourceCulture);
            }
        }
        
        public static string ITEM_DRUNK {
            get {
                return ResourceManager.GetString("ITEM_DRUNK", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_DRINK {
            get {
                return ResourceManager.GetString("NOTHING_TO_DRINK", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_CUT {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CUT", resourceCulture);
            }
        }
        
        public static string NOT_TIRED {
            get {
                return ResourceManager.GetString("NOT_TIRED", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_SMELL {
            get {
                return ResourceManager.GetString("NOTHING_TO_SMELL", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_TASTE {
            get {
                return ResourceManager.GetString("NOTHING_TO_TASTE", resourceCulture);
            }
        }
        
        public static string WHAT_TO_TASTE {
            get {
                return ResourceManager.GetString("WHAT_TO_TASTE", resourceCulture);
            }
        }
        
        public static string ITEM_UNLOCKED_WITH_KEY_FROM_INVENTORY {
            get {
                return ResourceManager.GetString("ITEM_UNLOCKED_WITH_KEY_FROM_INVENTORY", resourceCulture);
            }
        }
        
        public static string ALREADY_LOCKED {
            get {
                return ResourceManager.GetString("ALREADY_LOCKED", resourceCulture);
            }
        }
        
        public static string IMPOSSIBLE_LOCK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_LOCK", resourceCulture);
            }
        }
        
        public static string ITEM_LOCKED_WITH_KEY_FROM_INVENTORY {
            get {
                return ResourceManager.GetString("ITEM_LOCKED_WITH_KEY_FROM_INVENTORY", resourceCulture);
            }
        }
        
        public static string ITEM_LOCKED {
            get {
                return ResourceManager.GetString("ITEM_LOCKED", resourceCulture);
            }
        }
        
        public static string NOT_CLIMBED {
            get {
                return ResourceManager.GetString("NOT_CLIMBED", resourceCulture);
            }
        }
        
        public static string NOT_CLIMBED_ON_ITEM {
            get {
                return ResourceManager.GetString("NOT_CLIMBED_ON_ITEM", resourceCulture);
            }
        }
        
        public static string ALREADY_CLIMBED_ITEM {
            get {
                return ResourceManager.GetString("ALREADY_CLIMBED_ITEM", resourceCulture);
            }
        }
        
        public static string ALREADY_WEARING {
            get {
                return ResourceManager.GetString("ALREADY_WEARING", resourceCulture);
            }
        }
        
        public static string PULLON_WEARABLE {
            get {
                return ResourceManager.GetString("PULLON_WEARABLE", resourceCulture);
            }
        }
        
        public static string NOTHING_TO_WEAR {
            get {
                return ResourceManager.GetString("NOTHING_TO_WEAR", resourceCulture);
            }
        }
        
        public static string PULL_DOES_NOT_WORK {
            get {
                return ResourceManager.GetString("PULL_DOES_NOT_WORK", resourceCulture);
            }
        }
    }
}
