//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaseGrammar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseGrammar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.BaseGrammar", typeof(BaseGrammar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ACCUSATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_INDEFINITEARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_INDEFINITEARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_ARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_ARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_ARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_ARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_ARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_ARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_INDEFINITEARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_INDEFINITEARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string DATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string DATIVE_INDEFINITEARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_INDEFINITEARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string DATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_ARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_ARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_ARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string DATIVE_ARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string DATIVE_ARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string DATIVE_ARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_ARTICLE_PLURAL {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_PLURAL", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_PRONOUN_YOU {
            get {
                return ResourceManager.GetString("NOMINATIVE_PRONOUN_YOU", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_PRONOUN_HE {
            get {
                return ResourceManager.GetString("NOMINATIVE_PRONOUN_HE", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_PRONOUN_SHE {
            get {
                return ResourceManager.GetString("NOMINATIVE_PRONOUN_SHE", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_PRONOUN_IT {
            get {
                return ResourceManager.GetString("NOMINATIVE_PRONOUN_IT", resourceCulture);
            }
        }
        
        internal static string DATIVE_PRONOUN_YOU {
            get {
                return ResourceManager.GetString("DATIVE_PRONOUN_YOU", resourceCulture);
            }
        }
        
        internal static string DATIVE_PRONOUN_HE {
            get {
                return ResourceManager.GetString("DATIVE_PRONOUN_HE", resourceCulture);
            }
        }
        
        internal static string DATIVE_PRONOUN_SHE {
            get {
                return ResourceManager.GetString("DATIVE_PRONOUN_SHE", resourceCulture);
            }
        }
        
        internal static string DATIVE_PRONOUN_IT {
            get {
                return ResourceManager.GetString("DATIVE_PRONOUN_IT", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_PRONOUN_YOU {
            get {
                return ResourceManager.GetString("ACCUSATIVE_PRONOUN_YOU", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_PRONOUN_HE {
            get {
                return ResourceManager.GetString("ACCUSATIVE_PRONOUN_HE", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_PRONOUN_SHE {
            get {
                return ResourceManager.GetString("ACCUSATIVE_PRONOUN_SHE", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_PRONOUN_IT {
            get {
                return ResourceManager.GetString("ACCUSATIVE_PRONOUN_IT", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_PRONOUN_THEY {
            get {
                return ResourceManager.GetString("NOMINATIVE_PRONOUN_THEY", resourceCulture);
            }
        }
        
        internal static string DATIVE_PRONOUN_THEY {
            get {
                return ResourceManager.GetString("DATIVE_PRONOUN_THEY", resourceCulture);
            }
        }
        
        internal static string ACCUSATIVE_PRONOUN_THEY {
            get {
                return ResourceManager.GetString("ACCUSATIVE_PRONOUN_THEY", resourceCulture);
            }
        }
        
        internal static string DATIVE_ARTICLE_PLURAL {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_PLURAL", resourceCulture);
            }
        }
        
        internal static string COMBINED_PREPOSITIONS_AND_ARTICLES {
            get {
                return ResourceManager.GetString("COMBINED_PREPOSITIONS_AND_ARTICLES", resourceCulture);
            }
        }
        
        internal static string UMLAUTS {
            get {
                return ResourceManager.GetString("UMLAUTS", resourceCulture);
            }
        }
        
        internal static string NOMINATIVE_ARTICLE_PLURAL {
            get {
                return ResourceManager.GetString("NOMINATIVE_ARTICLE_PLURAL", resourceCulture);
            }
        }
        
        internal static string ADJECTIVE_DECLINATION_NOMINATIVE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("ADJECTIVE_DECLINATION_NOMINATIVE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ADJECTIVE_DECLINATION_NOMINATIVE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("ADJECTIVE_DECLINATION_NOMINATIVE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ADJECTIVE_DECLINATION_NOMINATIVE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("ADJECTIVE_DECLINATION_NOMINATIVE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        internal static string ADJECTIVE_DECLINATION_NOMINATIVE_PLURAL {
            get {
                return ResourceManager.GetString("ADJECTIVE_DECLINATION_NOMINATIVE_PLURAL", resourceCulture);
            }
        }
    }
}
