//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.BaseDescriptions", typeof(BaseDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du trägst im Moment Gegenstände mit einem Gesamtgewicht von {0, 0:F3} kg. Du kannst noch {1, 0:F3} kg zusätzlich tragen..
        /// </summary>
        public static string ACTUAL_PAYLOAD {
            get {
                return ResourceManager.GetString("ACTUAL_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits zerbrochen..
        /// </summary>
        public static string ALREADY_BROKEN {
            get {
                return ResourceManager.GetString("ALREADY_BROKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klettere zunächst von Deiner aktuellen Position wieder nach unten..
        /// </summary>
        public static string ALREADY_CLIMBED {
            get {
                return ResourceManager.GetString("ALREADY_CLIMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits geschlossen..
        /// </summary>
        public static string ALREADY_CLOSED {
            get {
                return ResourceManager.GetString("ALREADY_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits geöffnet..
        /// </summary>
        public static string ALREADY_OPEN {
            get {
                return ResourceManager.GetString("ALREADY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist bereits entriegelt..
        /// </summary>
        public static string ALREADY_UNLOCKED {
            get {
                return ResourceManager.GetString("ALREADY_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Bezeichnungen für Personen und Gegenstände.
        /// </summary>
        public static string ALTER_EGO {
            get {
                return ResourceManager.GetString("ALTER_EGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Begriffe kannst Du für &apos;{0}&apos; ebenfalls benutzen: .
        /// </summary>
        public static string ALTER_EGO_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALTER_EGO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage eine Person.
        /// </summary>
        public static string ASK {
            get {
                return ResourceManager.GetString("ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dazu kann ich Ihnen im Moment nichts sagen&quot;, antwortet {0}..
        /// </summary>
        public static string ASK_FOR_INVISIBLE_OBJECT {
            get {
                return ResourceManager.GetString("ASK_FOR_INVISIBLE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verhindern, dass Du weitere Gegenstände mitnehmen kannst..
        /// </summary>
        public static string BLOCK_PICKUP_PLURAL {
            get {
                return ResourceManager.GetString("BLOCK_PICKUP_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verhindert, dass Du weitere Gegenstände mitnehmen kannst..
        /// </summary>
        public static string BLOCK_PICKUP_SINGLE {
            get {
                return ResourceManager.GetString("BLOCK_PICKUP_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zerbrich, bzw. zerstöre einen Gegenstand.
        /// </summary>
        public static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufe einen Gegenstand.
        /// </summary>
        public static string BUY {
            get {
                return ResourceManager.GetString("BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Benutze das Kommando &apos;name&apos;, um Dir im Spiel einen Namen zu geben.&gt;&gt;.
        /// </summary>
        public static string CHANGE_NAME {
            get {
                return ResourceManager.GetString("CHANGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Person sehe ich hier nicht..
        /// </summary>
        public static string CHARACTER_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("CHARACTER_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klettere, bzw. steige auf ein Objekt..
        /// </summary>
        public static string CLIMB {
            get {
                return ResourceManager.GetString("CLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließe einen Gegenstand.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zum Spiel abrufen.
        /// </summary>
        public static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steige von dem Objekt herab, auf das Du geklettert bist..
        /// </summary>
        public static string DESCEND {
            get {
                return ResourceManager.GetString("DESCEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist heruntergestiegen..
        /// </summary>
        public static string DESCENDING {
            get {
                return ResourceManager.GetString("DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das scheint nicht zu funktionieren..
        /// </summary>
        public static string DOES_NOT_WORK {
            get {
                return ResourceManager.GetString("DOES_NOT_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Runter&quot;.
        /// </summary>
        public static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasse einen Gegenstand fallen.
        /// </summary>
        public static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Osten&quot;.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iss etwas.
        /// </summary>
        public static string EAT {
            get {
                return ResourceManager.GetString("EAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Spiel wurde gespeichert unter: {0}.
        /// </summary>
        public static string GAME_SAVED {
            get {
                return ResourceManager.GetString("GAME_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sie.
        /// </summary>
        public static string GENDER_FEMALE {
            get {
                return ResourceManager.GetString("GENDER_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er.
        /// </summary>
        public static string GENDER_MALE {
            get {
                return ResourceManager.GetString("GENDER_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string GENDER_UNKNOWN {
            get {
                return ResourceManager.GetString("GENDER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überreiche einen Gegenstand.
        /// </summary>
        public static string GIVE {
            get {
                return ResourceManager.GetString("GIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehe zu einem Ort.
        /// </summary>
        public static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {0},.
        /// </summary>
        public static string HELLO_NAME {
            get {
                return ResourceManager.GetString("HELLO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo Fremder,.
        /// </summary>
        public static string HELLO_STRANGER {
            get {
                return ResourceManager.GetString("HELLO_STRANGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige diese Hilfeseite.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Schreibe &apos;hilfe&apos;, um Hilfe zu erhalten. &gt;&gt;.
        /// </summary>
        public static string HELP_WANTED {
            get {
                return ResourceManager.GetString("HELP_WANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kannst Du hier sehen..
        /// </summary>
        public static string HERE {
            get {
                return ResourceManager.GetString("HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sind hier..
        /// </summary>
        public static string HERE_PLURAL {
            get {
                return ResourceManager.GetString("HERE_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist hier..
        /// </summary>
        public static string HERE_SINGLE {
            get {
                return ResourceManager.GetString("HERE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltet das kontextbasierte Tipp-System an oder aus..
        /// </summary>
        public static string HINT {
            get {
                return ResourceManager.GetString("HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Tipp-System wurde deaktiviert..
        /// </summary>
        public static string HINT_OFF {
            get {
                return ResourceManager.GetString("HINT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Tipp-System wurde aktiviert..
        /// </summary>
        public static string HINT_ON {
            get {
                return ResourceManager.GetString("HINT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste alle bisherigen Kommandos auf.
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst das nicht zerstören..
        /// </summary>
        public static string IMPOSSIBLE_BREAK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du das denn zerstören? Hast Du vielleicht irgendein entsprechendes Werkzeug?.
        /// </summary>
        public static string IMPOSSIBLE_BREAK_ITEM {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_BREAK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaah, eine Entführung? Das ist bestimmt ein ganz tolle Idee....
        /// </summary>
        public static string IMPOSSIBLE_CHARACTER_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CHARACTER_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keinen Grund, das zu tun..
        /// </summary>
        public static string IMPOSSIBLE_CLIMB {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das funktioniert nicht wie erwartet..
        /// </summary>
        public static string IMPOSSIBLE_CLOSE {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht fallen lassen. Ist es noch mit einem anderen Gegenstand verbunden?.
        /// </summary>
        public static string IMPOSSIBLE_DROP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar lässt sich das nicht öffnen..
        /// </summary>
        public static string IMPOSSIBLE_OPEN {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh wirklich? Mal ganz realistisch. Das kannst Du nicht mitnehmen!|Ich glaube nicht, dass Du das gebrauchen kannst|Nein, auf keinen Fall!|Ein Tipp: Du brauchst das nicht und deshalb lassen wir das liegen..
        /// </summary>
        public static string IMPOSSIBLE_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst das nicht mitnehmen..
        /// </summary>
        public static string IMPOSSIBLE_SINGLE_ITEM_PICKUP {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_SINGLE_ITEM_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du denn {0} aufschliessen? Hast Du vielleicht irgendeinen passenden Schlüssel?.
        /// </summary>
        public static string IMPOSSIBLE_UNLOCK {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du das denn aufschliessen? Hast Du vielleicht irgendeinen passenden Schlüssel?.
        /// </summary>
        public static string IMPOSSIBLE_UNLOCK_SURROUNDINGS {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK_SURROUNDINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lässt sich ohne passenden Schlüssel oder einen schlüsselähnlichen Gegenstand nicht öffnen. {1} ist auf jeden Fall nicht passend..
        /// </summary>
        public static string IMPOSSIBLE_UNLOCK_WITH_WRONG_KEY {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_UNLOCK_WITH_WRONG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Deine mitgeführten Gegenstände.
        /// </summary>
        public static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trägst Du bei Dir..
        /// </summary>
        public static string INVENTORY {
            get {
                return ResourceManager.GetString("INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trägt {0} bei sich..
        /// </summary>
        public static string INVENTORY_TEMPLATE {
            get {
                return ResourceManager.GetString("INVENTORY_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hm? Kannst es sein, dass Du den Gegenstand schon besitzt?.
        /// </summary>
        public static string ITEM_ALREADY_OWNED {
            get {
                return ResourceManager.GetString("ITEM_ALREADY_OWNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist auf {0} gestiegen..
        /// </summary>
        public static string ITEM_CLIMBED {
            get {
                return ResourceManager.GetString("ITEM_CLIMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} fallen gelassen..
        /// </summary>
        public static string ITEM_DROP {
            get {
                return ResourceManager.GetString("ITEM_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} gegessen..
        /// </summary>
        public static string ITEM_EATEN {
            get {
                return ResourceManager.GetString("ITEM_EATEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das wirkt nicht so, als könne man es essen!.
        /// </summary>
        public static string ITEM_NOT_EATABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_EATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht auf- oder zugeschlossen werden..
        /// </summary>
        public static string ITEM_NOT_LOCKABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_LOCKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das geht nicht. Du hast den Gegenstand offensichtlich gar nicht bei Dir. Oder ist er noch in einem anderen Behälter?.
        /// </summary>
        public static string ITEM_NOT_OWNED {
            get {
                return ResourceManager.GetString("ITEM_NOT_OWNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist nicht möglich, sich auf {0} zu setzen..
        /// </summary>
        public static string ITEM_NOT_SEATABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_SEATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesen Gegenstand sehe ich hier nicht!.
        /// </summary>
        public static string ITEM_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheinbar gibt es in diesem Raum nur eine richtige Sitzmöglichkeit. Daher nimmst Du einfach auf {0} Platz..
        /// </summary>
        public static string ITEM_ONLY_SEAT {
            get {
                return ResourceManager.GetString("ITEM_ONLY_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast {0} genommen..
        /// </summary>
        public static string ITEM_PICKUP {
            get {
                return ResourceManager.GetString("ITEM_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast auf {0} Platz genommen..
        /// </summary>
        public static string ITEM_SEATED {
            get {
                return ResourceManager.GetString("ITEM_SEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist aber abgeschlossen..
        /// </summary>
        public static string ITEM_STILL_LOCKED {
            get {
                return ResourceManager.GetString("ITEM_STILL_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht zerbrochen werden..
        /// </summary>
        public static string ITEM_UNBREAKABLE {
            get {
                return ResourceManager.GetString("ITEM_UNBREAKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich kenne und sehe nichts was &quot;{0}&quot; sein könnte..
        /// </summary>
        public static string ITEM_UNKNOWN {
            get {
                return ResourceManager.GetString("ITEM_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wurde aufgeschlossen..
        /// </summary>
        public static string ITEM_UNLOCKED {
            get {
                return ResourceManager.GetString("ITEM_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Springe hoch oder auf ein Objekt.
        /// </summary>
        public static string JUMP {
            get {
                return ResourceManager.GetString("JUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mir ist nicht klar, was Du hier als Schlüssel verwenden willst..
        /// </summary>
        public static string KEY_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("KEY_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist verbunden mit .
        /// </summary>
        public static string LINKED_TO {
            get {
                return ResourceManager.GetString("LINKED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verriegel einen Gegenstand.
        /// </summary>
        public static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaue Dir Örtlichkeiten, Personen oder Gegenstände an.
        /// </summary>
        public static string LOOK {
            get {
                return ResourceManager.GetString("LOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst momentan ein maximales Gewicht von {0, 0:F3} kg tragen..
        /// </summary>
        public static string MAX_PAYLOAD {
            get {
                return ResourceManager.GetString("MAX_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich verstehe Dich nicht! Was genau möchtest Du tun?.
        /// </summary>
        public static string MISCONCEPTION {
            get {
                return ResourceManager.GetString("MISCONCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf welche der Sitzgelegenheiten möchtest Du denn Platz nehmen? Das musst Du schon genauer bestimmen..
        /// </summary>
        public static string MORE_SEATS {
            get {
                return ResourceManager.GetString("MORE_SEATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Nord&quot;.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändere Deinen Spielernamen.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Nord-Ost&quot;.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du sagst &quot;{0}&quot;. Keine Reaktion!.
        /// </summary>
        public static string NO_ANSWER {
            get {
                return ResourceManager.GetString("NO_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensichtlich gibt es darüber nichts zu sagen..
        /// </summary>
        public static string NO_ANSWER_EXCEPTION {
            get {
                return ResourceManager.GetString("NO_ANSWER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du fragst &quot;{0}&quot;? Keine Reaktion!.
        /// </summary>
        public static string NO_ANSWER_TO_QUESTION {
            get {
                return ResourceManager.GetString("NO_ANSWER_TO_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irgendwie passiert nichts. Hattest Du vielleicht etwas anderes vor?.
        /// </summary>
        public static string NO_EVENT {
            get {
                return ResourceManager.GetString("NO_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier gibt es scheinbar keine Sitzmöglichkeit. Also bleibst Du einfach stehen..
        /// </summary>
        public static string NO_SEAT {
            get {
                return ResourceManager.GetString("NO_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst dort nicht hingehen!.
        /// </summary>
        public static string NO_WAY {
            get {
                return ResourceManager.GetString("NO_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Moment gibt es hier keine sichtbaren Wege. Vielleicht musst Du nur genau schauen, oder jemanden danach fragen?.
        /// </summary>
        public static string NO_WAYS {
            get {
                return ResourceManager.GetString("NO_WAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So wie es aussieht, sitzt Du gerade gar nicht..
        /// </summary>
        public static string NOT_SITTING {
            get {
                return ResourceManager.GetString("NOT_SITTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast aktuell keine Gegenstände bei Dir..
        /// </summary>
        public static string NOTHING {
            get {
                return ResourceManager.GetString("NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts passiert!.
        /// </summary>
        public static string NOTHING_HAPPENS {
            get {
                return ResourceManager.GetString("NOTHING_HAPPENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt hier keine Gegenstände die Du mitnehmen kannst..
        /// </summary>
        public static string NOTHING_TO_TAKE {
            get {
                return ResourceManager.GetString("NOTHING_TO_TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun geschlossen..
        /// </summary>
        public static string NOW_CLOSED {
            get {
                return ResourceManager.GetString("NOW_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun geöffnet..
        /// </summary>
        public static string NOW_OPEN {
            get {
                return ResourceManager.GetString("NOW_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Nord-West&quot;.
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das macht keinen Sinn. Du kannst das nicht kaufen..
        /// </summary>
        public static string ON_BUY_EXCEPTION {
            get {
                return ResourceManager.GetString("ON_BUY_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne einen Gegenstand.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit willst Du das bezahlen?.
        /// </summary>
        public static string PAY_WITH_WHAT {
            get {
                return ResourceManager.GetString("PAY_WITH_WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehe an einem Gegenstand.
        /// </summary>
        public static string PULL {
            get {
                return ResourceManager.GetString("PULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücke, bzw. schiebe oder stecke einen Gegenstand in etwas hinein.
        /// </summary>
        public static string PUSH {
            get {
                return ResourceManager.GetString("PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Glückwunsch! Du hast gerade die Quest &apos;{0}&apos; gelöst. &gt;&gt;.
        /// </summary>
        public static string QUEST_SOLVED {
            get {
                return ResourceManager.GetString("QUEST_SOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beende das Spiel.
        /// </summary>
        public static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spiel wird beendet..
        /// </summary>
        public static string QUIT_GAME {
            get {
                return ResourceManager.GetString("QUIT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügt dem internen Protokoll einen Kommentar hinzu..
        /// </summary>
        public static string REM {
            get {
                return ResourceManager.GetString("REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Tür scheint verschlossen zu sein..
        /// </summary>
        public static string ROOM_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("ROOM_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Süden&quot;.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dasselbe wolltest Du doch gerade schon machen?! Aber bitte....
        /// </summary>
        public static string SAME_ACTION_AGAIN {
            get {
                return ResourceManager.GetString("SAME_ACTION_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichert Deinen aktuellen Spielstand..
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heretic_savedgame.txt.
        /// </summary>
        public static string SAVE_NAME {
            get {
                return ResourceManager.GetString("SAVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprich mit einer Person.
        /// </summary>
        public static string SAY {
            get {
                return ResourceManager.GetString("SAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erreichte Wertung {0}/{1}.
        /// </summary>
        public static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Süd-Ost&quot;.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte Dich auf eine Sitzgelegenheit.
        /// </summary>
        public static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du sitzt gerade auf {0}..
        /// </summary>
        public static string SITTING_ON {
            get {
                return ResourceManager.GetString("SITTING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist aufgestanden..
        /// </summary>
        public static string STANDING_UP {
            get {
                return ResourceManager.GetString("STANDING_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stehe von einer Sitzgelegenheit auf.
        /// </summary>
        public static string STANDUP {
            get {
                return ResourceManager.GetString("STANDUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; ...drücke eine Taste, um das Spiel zu starten... &gt;&gt;.
        /// </summary>
        public static string START_THE_GAME {
            get {
                return ResourceManager.GetString("START_THE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selbst wenn das ginge, macht das gerade keinen Sinn..
        /// </summary>
        public static string SURROUNDING_NOT_SEATABLE {
            get {
                return ResourceManager.GetString("SURROUNDING_NOT_SEATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Süd-West&quot;.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm einen Gegenstand.
        /// </summary>
        public static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smalltalk mit einer Person.
        /// </summary>
        public static string TALK {
            get {
                return ResourceManager.GetString("TALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Gegenstand ist zu schwer, um ihn noch zu tragen! Vielleicht benötigst Du eine größere Transportmöglichkeit, oder Du wirfst einige Sachen weg..
        /// </summary>
        public static string TO_HEAVY {
            get {
                return ResourceManager.GetString("TO_HEAVY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mir ist nicht klar, was Du hier als Werkzeug verwenden willst..
        /// </summary>
        public static string TOOL_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("TOOL_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drehe einen Gegenstand, bzw. schließe oder öffne einen Gegenstand durch drehen.
        /// </summary>
        public static string TURN {
            get {
                return ResourceManager.GetString("TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entriegel einen Gegenstand.
        /// </summary>
        public static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Hoch&quot;.
        /// </summary>
        public static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutze einen Gegenstand.
        /// </summary>
        public static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtung &quot;Westen&quot;.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liegt in Richtung.
        /// </summary>
        public static string WAY {
            get {
                return ResourceManager.GetString("WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Weg scheint geschlossen zu sein. Musst Du vielleicht erst etwas öffnen?.
        /// </summary>
        public static string WAY_IS_CLOSED {
            get {
                return ResourceManager.GetString("WAY_IS_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Weg scheint versperrt zu sein. Vielleicht benötigst Du eine Art Schlüssel?.
        /// </summary>
        public static string WAY_IS_LOCKED {
            get {
                return ResourceManager.GetString("WAY_IS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige alle verfügbaren Wege.
        /// </summary>
        public static string WAYS {
            get {
                return ResourceManager.GetString("WAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Dinge hast Du angezogen: .
        /// </summary>
        public static string WEARING_ITEMS {
            get {
                return ResourceManager.GetString("WEARING_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Hm?&quot;, ist die verwunderte Antwort..
        /// </summary>
        public static string WHAT {
            get {
                return ResourceManager.GetString("WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibe oder tippe etwas.
        /// </summary>
        public static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit wird Dir das nicht gelingen!.
        /// </summary>
        public static string WRONG_BREAK_ITEM {
            get {
                return ResourceManager.GetString("WRONG_BREAK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} damit nicht aufschließen. Vielleicht probierst Du besser einen anderen Schlüssel?.
        /// </summary>
        public static string WRONG_KEY {
            get {
                return ResourceManager.GetString("WRONG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} damit nicht zerbrechen. Vielleicht probierst Du besser ein anderes Werkzeug?.
        /// </summary>
        public static string WRONG_TOOL {
            get {
                return ResourceManager.GetString("WRONG_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darin befinden sich:.
        /// </summary>
        public static string YOU_SEE {
            get {
                return ResourceManager.GetString("YOU_SEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sie trägt bei sich:.
        /// </summary>
        public static string YOU_SEE_FEMALE {
            get {
                return ResourceManager.GetString("YOU_SEE_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er trägt bei sich:.
        /// </summary>
        public static string YOU_SEE_MALE {
            get {
                return ResourceManager.GetString("YOU_SEE_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darin befindet sich:.
        /// </summary>
        public static string YOU_SEE_SINGULAR {
            get {
                return ResourceManager.GetString("YOU_SEE_SINGULAR", resourceCulture);
            }
        }
    }
}
