//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Grammar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grammar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.Grammar", typeof(Grammar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die.
        /// </summary>
        internal static string ACCUSATIVE_ARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den.
        /// </summary>
        internal static string ACCUSATIVE_ARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das.
        /// </summary>
        internal static string ACCUSATIVE_ARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_ARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine.
        /// </summary>
        internal static string ACCUSATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen.
        /// </summary>
        internal static string ACCUSATIVE_INDEFINITEARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_INDEFINITEARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein.
        /// </summary>
        internal static string ACCUSATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("ACCUSATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die.
        /// </summary>
        internal static string ARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("ARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der.
        /// </summary>
        internal static string ARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("ARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das.
        /// </summary>
        internal static string ARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("ARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der.
        /// </summary>
        internal static string DATIVE_ARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem.
        /// </summary>
        internal static string DATIVE_ARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem.
        /// </summary>
        internal static string DATIVE_ARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_ARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einer.
        /// </summary>
        internal static string DATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einem.
        /// </summary>
        internal static string DATIVE_INDEFINITEARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_INDEFINITEARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einem.
        /// </summary>
        internal static string DATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("DATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine.
        /// </summary>
        internal static string NOMINATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_INDEFINITEARTICLE_FEMALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein.
        /// </summary>
        internal static string NOMINATIVE_INDEFINITEARTICLE_MALE_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_INDEFINITEARTICLE_MALE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein.
        /// </summary>
        internal static string NOMINATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR {
            get {
                return ResourceManager.GetString("NOMINATIVE_INDEFINITEARTICLE_NEUTRUM_SINGULAR", resourceCulture);
            }
        }
    }
}
