//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.HelpDescriptions", typeof(HelpDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beispiele: .
        /// </summary>
        internal static string EXAMPLES {
            get {
                return ResourceManager.GetString("EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einige generelle Hinweise:.
        /// </summary>
        internal static string HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schaue.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_LOOK {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schaue auf den teppich.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_II {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schaue teppich.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_III {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist sehr wichtig, dass Du Dir Deine Umgebung ganz genau anschaust. Jeder noch so kleine Hinweis kann von Bedeutung sein. Um das zu tun, benutzt Du das Kommando.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_PART_I {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_PART_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [zeigt die Beschreibung des Teppichs, aber nur, wenn es auch einen Teppich in dem aktuellen Raum gibt].
        /// </summary>
        internal static string ITEM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [das ist die kurze Schreibweise und die zeigt Dir ebenfalls die Beschreibung des Teppichs].
        /// </summary>
        internal static string ITEM_DESCRIPTION_SHORT {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string PROMPT {
            get {
                return ResourceManager.GetString("PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [zeigt die Beschreibung des aktuellen Raums].
        /// </summary>
        internal static string ROOM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ROOM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Kommandos stehen Dir zur Verfügung:.
        /// </summary>
        internal static string VERBS {
            get {
                return ResourceManager.GetString("VERBS", resourceCulture);
            }
        }
    }
}
