//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpDescriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpDescriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.HelpDescriptions", typeof(HelpDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string HELP_GENERAL_INSTRUCTION_PART_I {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_PART_I", resourceCulture);
            }
        }
        
        internal static string HELP_GENERAL_INSTRUCTION_LOOK {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK", resourceCulture);
            }
        }
        
        internal static string VERBS {
            get {
                return ResourceManager.GetString("VERBS", resourceCulture);
            }
        }
        
        internal static string EXAMPLES {
            get {
                return ResourceManager.GetString("EXAMPLES", resourceCulture);
            }
        }
        
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_II {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_II", resourceCulture);
            }
        }
        
        internal static string PROMPT {
            get {
                return ResourceManager.GetString("PROMPT", resourceCulture);
            }
        }
        
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_III {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_III", resourceCulture);
            }
        }
        
        internal static string ROOM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ROOM_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ITEM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ITEM_DESCRIPTION_SHORT {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION_SHORT", resourceCulture);
            }
        }
        
        internal static string VERBS_DIRECTIONS {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS", resourceCulture);
            }
        }
        
        internal static string VERBS_DIRECTIONS_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS_EXAMPLE_I", resourceCulture);
            }
        }
        
        internal static string VERBS_DIRECTIONS_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS_EXAMPLE_II", resourceCulture);
            }
        }
        
        internal static string VERBS_DIRECTIONS_EXAMPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS_EXAMPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_METAINFO {
            get {
                return ResourceManager.GetString("VERBS_METAINFO", resourceCulture);
            }
        }
        
        internal static string VERBS_METAINFO_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_I", resourceCulture);
            }
        }
        
        internal static string VERBS_METAINFO_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_II", resourceCulture);
            }
        }
        
        internal static string VERBS_METAINFO_EXAMPLE_III {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_III", resourceCulture);
            }
        }
        
        internal static string VERBS_METAINFO_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_METAINFO_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_TALKS {
            get {
                return ResourceManager.GetString("VERBS_TALKS", resourceCulture);
            }
        }
        
        internal static string VERBS_TALK_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_I", resourceCulture);
            }
        }
        
        internal static string VERBS_TALK_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_TALK_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_II", resourceCulture);
            }
        }
        
        internal static string VERBS_TALK_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_TALK_EXAMPLE_III {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_III", resourceCulture);
            }
        }
        
        internal static string VERBS_TALK_EXAMPLE_III_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_III_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_I", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_II", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_III {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_III", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_III_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_III_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_CONTAINER {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER", resourceCulture);
            }
        }
        
        internal static string VERBS_CONTAINER_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_I", resourceCulture);
            }
        }
        
        internal static string VERBS_CONTAINER_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_CONTAINER_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_II", resourceCulture);
            }
        }
        
        internal static string VERBS_CONTAINER_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_IV {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_IV", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_IV_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_IV_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_V {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_V", resourceCulture);
            }
        }
        
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_V_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_V_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_IV {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_IV", resourceCulture);
            }
        }
        
        internal static string ITEM_DESCRIPTION_ALTERNATIVE {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION_ALTERNATIVE", resourceCulture);
            }
        }
        
        internal static string VERBS_INDIVIDUAL {
            get {
                return ResourceManager.GetString("VERBS_INDIVIDUAL", resourceCulture);
            }
        }
    }
}
