//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.HelpDescriptions", typeof(HelpDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beispiele: .
        /// </summary>
        internal static string EXAMPLES {
            get {
                return ResourceManager.GetString("EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einige generelle Hinweise:.
        /// </summary>
        internal static string HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schaue.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_LOOK {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schaue auf den teppich.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_II {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schaue teppich.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_LOOK_III {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_LOOK_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist sehr wichtig, dass Du Dir Deine Umgebung ganz genau anschaust. Jeder noch so kleine Hinweis kann von Bedeutung sein. Um das zu tun, benutzt Du das Kommando.
        /// </summary>
        internal static string HELP_GENERAL_INSTRUCTION_PART_I {
            get {
                return ResourceManager.GetString("HELP_GENERAL_INSTRUCTION_PART_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [zeigt die Beschreibung des Teppichs, aber nur, wenn es auch einen Teppich in dem aktuellen Raum gibt].
        /// </summary>
        internal static string ITEM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [das ist die kurze Schreibweise und die zeigt Dir ebenfalls die Beschreibung des Teppichs].
        /// </summary>
        internal static string ITEM_DESCRIPTION_SHORT {
            get {
                return ResourceManager.GetString("ITEM_DESCRIPTION_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string PROMPT {
            get {
                return ResourceManager.GetString("PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [zeigt die Beschreibung des aktuellen Raums].
        /// </summary>
        internal static string ROOM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ROOM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Kommandos stehen Dir zur Verfügung:.
        /// </summary>
        internal static string VERBS {
            get {
                return ResourceManager.GetString("VERBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaktion mit ab- und verschließbaren Gegenständen:.
        /// </summary>
        internal static string VERBS_CONTAINER {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to öffne kiste.
        /// </summary>
        internal static string VERBS_CONTAINER_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [die Kiste wird geöffnet, sofern sie nicht abgeschlossen ist, bzw. man sie auch wirklich öffnen kann.].
        /// </summary>
        internal static string VERBS_CONTAINER_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entriegel schloß mit grünem schlüssel.
        /// </summary>
        internal static string VERBS_CONTAINER_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [das Schloß wird mit dem passenden Schlüssel aufgeschlossen.].
        /// </summary>
        internal static string VERBS_CONTAINER_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_CONTAINER_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungsrichtungen:.
        /// </summary>
        internal static string VERBS_DIRECTIONS {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [der Spieler bewegt sich an den westlich angrenzenden Ort.].
        /// </summary>
        internal static string VERBS_DIRECTIONS_EXAMPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS_EXAMPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to westen.
        /// </summary>
        internal static string VERBS_DIRECTIONS_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS_EXAMPLE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w.
        /// </summary>
        internal static string VERBS_DIRECTIONS_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_DIRECTIONS_EXAMPLE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaktion mit einem Gegenstand:.
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zerbrich die scheibe mit dem stein.
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [spricht für sich.].
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nimm den stein.
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [hebt den Stein auf und überführt ihn ins Inventar.].
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nimm.
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_III {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [hebt alle Gegenstände im Raum auf, die frei zugänglich sind.].
        /// </summary>
        internal static string VERBS_INTERACT_ITEMS_EXAMPLE_III_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_INTERACT_ITEMS_EXAMPLE_III_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metainformationen:.
        /// </summary>
        internal static string VERBS_METAINFO {
            get {
                return ResourceManager.GetString("VERBS_METAINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter teppich.
        /// </summary>
        internal static string VERBS_METAINFO_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [zeigt an, welcher Begriff in dieser Situation synonym für Teppich benutzt werden kann.].
        /// </summary>
        internal static string VERBS_METAINFO_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mein Name ist Marc.
        /// </summary>
        internal static string VERBS_METAINFO_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ändert den Spielernamen, der u.a. im Inventar angezeigt wird.].
        /// </summary>
        internal static string VERBS_METAINFO_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name Marc.
        /// </summary>
        internal static string VERBS_METAINFO_EXAMPLE_III {
            get {
                return ResourceManager.GetString("VERBS_METAINFO_EXAMPLE_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rede mit dem Barkeeper.
        /// </summary>
        internal static string VERBS_TALK_EXAMPLE_I {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [falls der Barkeeper mit Dir reden will, wird ein kurzes (vorgegebenes) Gespräch wiedergegeben. Die Möglichkeit einer Antwort besteht nicht.].
        /// </summary>
        internal static string VERBS_TALK_EXAMPLE_I_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_I_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frag den Barkeeper nach dem Wiskey.
        /// </summary>
        internal static string VERBS_TALK_EXAMPLE_II {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [falls der Barkeeper zu dem Glas etwas zu sagen hat, gibt er Dir eine Auskunft. Dient als Einstieg in ein echtes Gespräch.].
        /// </summary>
        internal static string VERBS_TALK_EXAMPLE_II_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_II_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sag ja zum Barkeeper.
        /// </summary>
        internal static string VERBS_TALK_EXAMPLE_III {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [hiermit kann eine Antwort auf eine Frage gegeben, oder ein Gespräch weitergeführt werden.].
        /// </summary>
        internal static string VERBS_TALK_EXAMPLE_III_DESCRIPTION {
            get {
                return ResourceManager.GetString("VERBS_TALK_EXAMPLE_III_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaktion mit einem Charakter:.
        /// </summary>
        internal static string VERBS_TALKS {
            get {
                return ResourceManager.GetString("VERBS_TALKS", resourceCulture);
            }
        }
    }
}
