//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Verbs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Verbs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.Verbs", typeof(Verbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ASK {
            get {
                return ResourceManager.GetString("ASK", resourceCulture);
            }
        }
        
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        internal static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        internal static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        internal static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        internal static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        internal static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        internal static string JUMP {
            get {
                return ResourceManager.GetString("JUMP", resourceCulture);
            }
        }
        
        internal static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        internal static string LOOK {
            get {
                return ResourceManager.GetString("LOOK", resourceCulture);
            }
        }
        
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        internal static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        internal static string SAY {
            get {
                return ResourceManager.GetString("SAY", resourceCulture);
            }
        }
        
        internal static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        internal static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        internal static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        internal static string TALK {
            get {
                return ResourceManager.GetString("TALK", resourceCulture);
            }
        }
        
        internal static string TURN {
            get {
                return ResourceManager.GetString("TURN", resourceCulture);
            }
        }
        
        internal static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        internal static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        internal static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        internal static string WAYS {
            get {
                return ResourceManager.GetString("WAYS", resourceCulture);
            }
        }
        
        internal static string ALTER_EGO {
            get {
                return ResourceManager.GetString("ALTER_EGO", resourceCulture);
            }
        }
        
        internal static string BUY {
            get {
                return ResourceManager.GetString("BUY", resourceCulture);
            }
        }
        
        internal static string GIVE {
            get {
                return ResourceManager.GetString("GIVE", resourceCulture);
            }
        }
        
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        internal static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        internal static string STANDUP {
            get {
                return ResourceManager.GetString("STANDUP", resourceCulture);
            }
        }
        
        internal static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
        
        internal static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        internal static string PULL {
            get {
                return ResourceManager.GetString("PULL", resourceCulture);
            }
        }
        
        internal static string PUSH {
            get {
                return ResourceManager.GetString("PUSH", resourceCulture);
            }
        }
        
        internal static string CLIMB {
            get {
                return ResourceManager.GetString("CLIMB", resourceCulture);
            }
        }
        
        internal static string DESCEND {
            get {
                return ResourceManager.GetString("DESCEND", resourceCulture);
            }
        }
        
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        internal static string HINT {
            get {
                return ResourceManager.GetString("HINT", resourceCulture);
            }
        }
        
        internal static string REM {
            get {
                return ResourceManager.GetString("REM", resourceCulture);
            }
        }
        
        internal static string READ {
            get {
                return ResourceManager.GetString("READ", resourceCulture);
            }
        }
        
        internal static string WAIT {
            get {
                return ResourceManager.GetString("WAIT", resourceCulture);
            }
        }
        
        internal static string ANSWER {
            get {
                return ResourceManager.GetString("ANSWER", resourceCulture);
            }
        }
        
        internal static string KINDLE {
            get {
                return ResourceManager.GetString("KINDLE", resourceCulture);
            }
        }
        
        internal static string CUT {
            get {
                return ResourceManager.GetString("CUT", resourceCulture);
            }
        }
        
        internal static string DRINK {
            get {
                return ResourceManager.GetString("DRINK", resourceCulture);
            }
        }
        
        internal static string EAT {
            get {
                return ResourceManager.GetString("EAT", resourceCulture);
            }
        }
        
        internal static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        internal static string LISTEN {
            get {
                return ResourceManager.GetString("LISTEN", resourceCulture);
            }
        }
        
        internal static string PUTON {
            get {
                return ResourceManager.GetString("PUTON", resourceCulture);
            }
        }
        
        internal static string SHOW {
            get {
                return ResourceManager.GetString("SHOW", resourceCulture);
            }
        }
        
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        internal static string SMELL {
            get {
                return ResourceManager.GetString("SMELL", resourceCulture);
            }
        }
        
        internal static string SWITCHON {
            get {
                return ResourceManager.GetString("SWITCHON", resourceCulture);
            }
        }
        
        internal static string TAKEOFF {
            get {
                return ResourceManager.GetString("TAKEOFF", resourceCulture);
            }
        }
        
        internal static string TASTE {
            get {
                return ResourceManager.GetString("TASTE", resourceCulture);
            }
        }
        
        internal static string TELL {
            get {
                return ResourceManager.GetString("TELL", resourceCulture);
            }
        }
        
        internal static string THROW {
            get {
                return ResourceManager.GetString("THROW", resourceCulture);
            }
        }
        
        internal static string WEAR {
            get {
                return ResourceManager.GetString("WEAR", resourceCulture);
            }
        }
        
        internal static string TOBE {
            get {
                return ResourceManager.GetString("TOBE", resourceCulture);
            }
        }
        
        internal static string SWITCHOFF {
            get {
                return ResourceManager.GetString("SWITCHOFF", resourceCulture);
            }
        }
        
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        internal static string DISCONNECT {
            get {
                return ResourceManager.GetString("DISCONNECT", resourceCulture);
            }
        }
        
        internal static string RESTART {
            get {
                return ResourceManager.GetString("RESTART", resourceCulture);
            }
        }
        
        internal static string REVERT {
            get {
                return ResourceManager.GetString("REVERT", resourceCulture);
            }
        }
    }
}
