//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Verbs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Verbs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.Verbs", typeof(Verbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter|Alterego|Alternativ|Alternative|Alias.
        /// </summary>
        internal static string ALTER_EGO {
            get {
                return ResourceManager.GetString("ALTER_EGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frag|Frage.
        /// </summary>
        internal static string ASK {
            get {
                return ResourceManager.GetString("ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zerbrich|Zerbreche|Brich|Breche|Brech|Zerstöre|Zerstör|Zerschlage|Zerschlag.
        /// </summary>
        internal static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezahle|Bezahl|Zahle|Zahl|Kaufe|Kauf.
        /// </summary>
        internal static string BUY {
            get {
                return ResourceManager.GetString("BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließe|Schließ|Schliesse|Schliess.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits|Info|Contribute|Contrib.
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runter.
        /// </summary>
        internal static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg|verliere|Drop.
        /// </summary>
        internal static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osten|Ost|O|E.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iss|Ess|Esse.
        /// </summary>
        internal static string EAT {
            get {
                return ResourceManager.GetString("EAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib|Gebe.
        /// </summary>
        internal static string GIVE {
            get {
                return ResourceManager.GetString("GIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehe|Geh|Go|G.
        /// </summary>
        internal static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe|Help.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History|Hist|Verlauf.
        /// </summary>
        internal static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventar|inv.
        /// </summary>
        internal static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring|Springe.
        /// </summary>
        internal static string JUMP {
            get {
                return ResourceManager.GetString("JUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verriegel|Verriegeln|Sperren|Sperre|Verschließe|Verschließ|Lock.
        /// </summary>
        internal static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaue|Schau|Lies|Untersuche|U|Zeige|Zeig|Look|L|Show.
        /// </summary>
        internal static string LOOK {
            get {
                return ResourceManager.GetString("LOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norden|Nord|N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nord-Osten|NO|NE.
        /// </summary>
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nord-Westen|NW.
        /// </summary>
        internal static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne|Öffnen.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehe|Zieh.
        /// </summary>
        internal static string PULL {
            get {
                return ResourceManager.GetString("PULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücke|Drück|Schiebe|Schieb|Stecke|Steck.
        /// </summary>
        internal static string PUSH {
            get {
                return ResourceManager.GetString("PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit|Exit|Ende|Q.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süden|Süd|Sued|Sueden|S.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sag|Sage|Antworte.
        /// </summary>
        internal static string SAY {
            get {
                return ResourceManager.GetString("SAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score|Punkte|Fortschritt.
        /// </summary>
        internal static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süd-Osten|Sued-Osten|SO|SE.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setze|Setzen|Setz|Hinsetzen.
        /// </summary>
        internal static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufstehen|Hinstellen.
        /// </summary>
        internal static string STANDUP {
            get {
                return ResourceManager.GetString("STANDUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süd-Westen|Sued-Westen|SW.
        /// </summary>
        internal static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm|Nehme|Take.
        /// </summary>
        internal static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rede|Sprich.
        /// </summary>
        internal static string TALK {
            get {
                return ResourceManager.GetString("TALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drehe|Dreh.
        /// </summary>
        internal static string TURN {
            get {
                return ResourceManager.GetString("TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entriegel|Entriegeln|Entsperren|Entsperre|Entsperr|aufschließen|aufschliessen|Unlock.
        /// </summary>
        internal static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoch|Rauf.
        /// </summary>
        internal static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutze|Nutze|Binde|Bind|Verbinde|Verbind|Verzurre|Fixiere|Fixier|Befestige|Befestig.
        /// </summary>
        internal static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westen|West|W.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wege|Auswege|Weg|Ausweg.
        /// </summary>
        internal static string WAYS {
            get {
                return ResourceManager.GetString("WAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibe|Schreib|Schreiben|Tippen|Tip|Tippe|Tipp.
        /// </summary>
        internal static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
    }
}
