//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heretic.InteractiveFiction.Resources;


/// <summary>
///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
/// </summary>
// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Verbs
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Verbs()
    {
    }

    /// <summary>
    ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heretic.InteractiveFiction.Resources.Verbs", typeof(Verbs).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Alter|Alterego|Alternativ|Alternative ähnelt.
    /// </summary>
    internal static string ALTER_EGO
    {
        get
        {
            return ResourceManager.GetString("ALTER_EGO", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Frag|Frage ähnelt.
    /// </summary>
    internal static string ASK
    {
        get
        {
            return ResourceManager.GetString("ASK", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Bezahle|Bezahl|Zahle|Zahl|Kaufe|Kauf ähnelt.
    /// </summary>
    internal static string BUY
    {
        get
        {
            return ResourceManager.GetString("BUY", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Schließe|Schließ|Schliesse|Schliess ähnelt.
    /// </summary>
    internal static string CLOSE
    {
        get
        {
            return ResourceManager.GetString("CLOSE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Credits|Anerkennung|Anerkennungen|Referenz|Referenzen|Würdigung|Würdigungen ähnelt.
    /// </summary>
    internal static string CREDITS
    {
        get
        {
            return ResourceManager.GetString("CREDITS", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Runter ähnelt.
    /// </summary>
    internal static string DOWN
    {
        get
        {
            return ResourceManager.GetString("DOWN", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Leg|verliere|Drop ähnelt.
    /// </summary>
    internal static string DROP
    {
        get
        {
            return ResourceManager.GetString("DROP", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Osten|Ost|O|E ähnelt.
    /// </summary>
    internal static string E
    {
        get
        {
            return ResourceManager.GetString("E", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Gib|Gebe ähnelt.
    /// </summary>
    internal static string GIVE
    {
        get
        {
            return ResourceManager.GetString("GIVE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Gehe|Geh|Go|G ähnelt.
    /// </summary>
    internal static string GO
    {
        get
        {
            return ResourceManager.GetString("GO", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe|Help|H ähnelt.
    /// </summary>
    internal static string HELP
    {
        get
        {
            return ResourceManager.GetString("HELP", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die History|Hist|All ähnelt.
    /// </summary>
    internal static string HISTORY
    {
        get
        {
            return ResourceManager.GetString("HISTORY", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Inventar|inv ähnelt.
    /// </summary>
    internal static string INV
    {
        get
        {
            return ResourceManager.GetString("INV", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Spring|Springe ähnelt.
    /// </summary>
    internal static string JUMP
    {
        get
        {
            return ResourceManager.GetString("JUMP", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Verriegeln|Verriegel|Sperren|Sperre|Verschließe|Verschließ|Lock ähnelt.
    /// </summary>
    internal static string LOCK
    {
        get
        {
            return ResourceManager.GetString("LOCK", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Schaue|Schau|Lies|Untersuche|Zeige|Zeig|Look|L|Show ähnelt.
    /// </summary>
    internal static string LOOK
    {
        get
        {
            return ResourceManager.GetString("LOOK", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Norden|Nord|N ähnelt.
    /// </summary>
    internal static string N
    {
        get
        {
            return ResourceManager.GetString("N", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
    /// </summary>
    internal static string NAME
    {
        get
        {
            return ResourceManager.GetString("NAME", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Nord-Osten|NO|NE ähnelt.
    /// </summary>
    internal static string NE
    {
        get
        {
            return ResourceManager.GetString("NE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Nord-Westen|NW ähnelt.
    /// </summary>
    internal static string NW
    {
        get
        {
            return ResourceManager.GetString("NW", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Öffne|Öffnen ähnelt.
    /// </summary>
    internal static string OPEN
    {
        get
        {
            return ResourceManager.GetString("OPEN", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Quit|Exit|Ende|Q ähnelt.
    /// </summary>
    internal static string QUIT
    {
        get
        {
            return ResourceManager.GetString("QUIT", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Süden|Süd|Sued|Sueden|S ähnelt.
    /// </summary>
    internal static string S
    {
        get
        {
            return ResourceManager.GetString("S", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Sag|Sage|Antworte ähnelt.
    /// </summary>
    internal static string SAY
    {
        get
        {
            return ResourceManager.GetString("SAY", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Score|Punkte|Fortschritt ähnelt.
    /// </summary>
    internal static string SCORE
    {
        get
        {
            return ResourceManager.GetString("SCORE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Süd-Osten|Sued-Osten|SO|SE ähnelt.
    /// </summary>
    internal static string SE
    {
        get
        {
            return ResourceManager.GetString("SE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Süd-Westen|Sued-Westen|SW ähnelt.
    /// </summary>
    internal static string SW
    {
        get
        {
            return ResourceManager.GetString("SW", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Nimm|Nehme|Take ähnelt.
    /// </summary>
    internal static string TAKE
    {
        get
        {
            return ResourceManager.GetString("TAKE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Rede|Sprich ähnelt.
    /// </summary>
    internal static string TALK
    {
        get
        {
            return ResourceManager.GetString("TALK", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Drehe|Dreh| ähnelt.
    /// </summary>
    internal static string TURN
    {
        get
        {
            return ResourceManager.GetString("TURN", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Entriegeln|Entriegel|Entsperren|Entsperre|Entsperr|aufschließen|aufschliessen|Unlock ähnelt.
    /// </summary>
    internal static string UNLOCK
    {
        get
        {
            return ResourceManager.GetString("UNLOCK", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Hoch|Rauf ähnelt.
    /// </summary>
    internal static string UP
    {
        get
        {
            return ResourceManager.GetString("UP", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Nutze|Benutze|Binde|Bind|Verbinde|Verbind|Verzurre|Fixiere|Fixier ähnelt.
    /// </summary>
    internal static string USE
    {
        get
        {
            return ResourceManager.GetString("USE", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Westen|West|W ähnelt.
    /// </summary>
    internal static string W
    {
        get
        {
            return ResourceManager.GetString("W", resourceCulture);
        }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Wege|Auswege|Weg|Ausweg ähnelt.
    /// </summary>
    internal static string WAYS
    {
        get
        {
            return ResourceManager.GetString("WAYS", resourceCulture);
        }
    }
}
